export const enum CustomId {
	AboutFeedback = "0",
	AboutIssue = "1",
	AboutFeedbackModal = "2",
	AboutFeedbackModalTitle = "3",
	AboutFeedbackModalDescription = "4",
	AboutIssueModal = "5",
	AboutIssueModalTitle = "6",
	AboutIssueModalDescription = "7",
	CatalogueSettings = "8",
	CatalogueViewRealms = "9",
	CatalogueViewElders = "10",
	CatalogueViewSeasons = "11",
	CatalogueViewEventYears = "12",
	CatalogueViewStarterPacks = "13",
	CatalogueViewSecretArea = "14",
	CatalogueViewPermanentEventStore = "15",
	CatalogueViewNestingWorkshop = "16",
	CatalogueViewReturningSpirits = "17",
	CatalogueSettingsEverything = "18",
	CatalogueBackToStart = "19",
	CatalogueViewStart = "20",
	CatalogueViewRealm = "21",
	CatalogueViewSpirit = "22",
	CatalogueRealmEverything = "23",
	CatalogueEldersEverything = "24",
	CatalogueViewSeason = "25",
	CatalogueSetSeasonItems = "26",
	CatalogueSeasonEverything = "27",
	CatalogueViewEventYear = "28",
	CatalogueViewEvent = "29",
	CatalogueViewOffer1 = "30",
	CatalogueViewOffer2 = "31",
	CatalogueViewOffer3 = "32",
	CatalogueItemsEverything = "33",
	ChecklistDailyQuestsComplete = "34",
	ChecklistDailyQuestsShow = "35",
	ChecklistSeasonalCandlesComplete = "36",
	ChecklistEyeOfEdenComplete = "37",
	ChecklistShardEruptionsComplete = "38",
	ChecklistShardEruptionsShow = "39",
	ChecklistEventTicketsComplete = "40",
	DailyGuidesSetup = "41",
	DailyGuidesQuestsReorder = "42",
	DailyGuidesLocale = "43",
	DailyGuidesDistribute = "44",
	DataDelete = "45",
	/**
	 * Discord Delivery creates a message that uses this.
	 */
	FriendshipActionsContribute = "46",
	GuessSpiritOption1 = "47",
	GuessSpiritOption2 = "48",
	GuessSpiritOption3 = "49",
	GuessEventOption1 = "50",
	GuessEventOption2 = "51",
	GuessEventOption3 = "52",
	GuessEnd = "53",
	GuessTryAgain = "54",
	GuessLeaderboardBack = "55",
	GuessLeaderboardNext = "56",
	HeartHistoryBack = "57",
	HeartHistoryNext = "58",
	MeSetBio = "59",
	MeDeleteBio = "60",
	MeDeleteAvatar = "61",
	MeDeleteBanner = "62",
	MeSetBioModal = "63",
	MetSetBioModalBio = "64",
	NotificationsSetup = "65",
	NotificationsSetupChannel = "66",
	NotificationsSetupRole = "67",
	NotificationsSetupOffset = "68",
	NotificationsViewSetup = "69",
	ScheduleViewDetailedBreakdown = "70",
	ScheduleViewOverview = "71",
	ScheduleDetailedBreakdownViewShardEruptions = "72",
	ScheduleDetailedBreakdownViewDailyGuides = "73",
	ScheduleDetailedBreakdownViewSpirit = "74",
	ScheduleDetailedBreakdownViewSpiritHistory = "75",
	ShardEruptionTodayToday = "76",
	ShardEruptionTodayBack = "77",
	ShardEruptionTodayNext = "78",
	ShardEruptionBrowse = "79",
	ShardEruptionBrowseDates1 = "80",
	ShardEruptionBrowseDates2 = "81",
	ShardEruptionBrowseDates3 = "82",
	ShardEruptionBrowseDates4 = "83",
	ShardEruptionBrowseDates5 = "84",
	ShardEruptionBrowseToday = "85",
	ShardEruptionBrowseBack = "86",
	ShardEruptionBrowseNext = "87",
	ShopSuggest = "88",
	ShopSuggestionModal = "89",
	ShopSuggestionModalSuggestion = "90",
	SkyProfileEdit = "91",
	SkyProfileViewReset = "92",
	SkyProfileExplorer1 = "93",
	SkyProfileExplorer2 = "94",
	SkyProfileExplorer3 = "95",
	SkyProfileExplorer4 = "96",
	SkyProfileExplorerBack = "97",
	SkyProfileExplorerNext = "98",
	SkyProfileExplorerViewLikes = "99",
	SkyProfileExplorerProfileBack = "100",
	SkyProfileExplorerProfileNext = "101",
	SkyProfileExplorerProfileLike = "102",
	SkyProfileViewExplorer = "103",
	SkyProfileExplorerProfileReport = "104",
	SkyProfileExplorerLikes1 = "105",
	SkyProfileExplorerLikes2 = "106",
	SkyProfileExplorerLikes3 = "107",
	SkyProfileExplorerLikes4 = "108",
	SkyProfileExplorerLikesBack = "109",
	SkyProfileExplorerLikesNext = "110",
	SkyProfileExplorerLikesProfileBack = "111",
	SkyProfileExplorerLikesProfileNext = "112",
	SkyProfileExplorerLikesProfileLike = "113",
	SkyProfileExplorerLikesProfileReport = "114",
	SkyProfileExplorerViewProfile = "115",
	SkyProfileExplorerLikesViewProfile = "116",
	SkyProfileExplorerConfirmReport = "117",
	SkyProfileReportModal = "118",
	SkyProfileReportModalReason = "119",
	SkyProfileNameModal = "120",
	SkyProfileNameModalName = "121",
	SkyProfileDescriptionModal = "122",
	SkyProfileDescriptionModalDescription = "123",
	SkyProfileWingedLight = "124",
	SkyProfileViewEdit = "125",
	SkyProfileHangoutModal = "126",
	SkyProfileHangoutModalHangout = "127",
	SkyProfileSeasons1 = "128",
	SkyProfileSeasons2 = "129",
	SkyProfilePlatforms = "130",
	SkyProfileReset = "131",
	SpiritsViewSpirit = "132",
	SpiritsHistoryBack = "133",
	SpiritsHistoryNext = "134",
}

export const SHARD_ERUPTION_DATES = [
	CustomId.ShardEruptionBrowseDates1,
	CustomId.ShardEruptionBrowseDates2,
	CustomId.ShardEruptionBrowseDates3,
	CustomId.ShardEruptionBrowseDates4,
	CustomId.ShardEruptionBrowseDates5,
] as const satisfies readonly CustomId[];

export const SKY_PROFILE_EXPLORERS = [
	CustomId.SkyProfileExplorer1,
	CustomId.SkyProfileExplorer2,
	CustomId.SkyProfileExplorer3,
	CustomId.SkyProfileExplorer4,
] as const satisfies readonly CustomId[];

export const SKY_PROFILE_EXPLORER_LIKES = [
	CustomId.SkyProfileExplorerLikes1,
	CustomId.SkyProfileExplorerLikes2,
	CustomId.SkyProfileExplorerLikes3,
	CustomId.SkyProfileExplorerLikes4,
] as const satisfies readonly CustomId[];
