export const enum CustomId {
	AboutFeedback = "0",
	AboutIssue = "1",
	AboutFeedbackModal = "2",
	AboutFeedbackModalTitle = "3",
	AboutFeedbackModalDescription = "4",
	AboutIssueModal = "5",
	AboutIssueModalTitle = "6",
	AboutIssueModalDescription = "7",
	AIFrequency = "8",
	CatalogueSettings = "9",
	CatalogueViewRealms = "10",
	CatalogueViewElders = "11",
	CatalogueViewSeasons = "12",
	CatalogueViewEventYears = "13",
	CatalogueViewStarterPacks = "14",
	CatalogueViewSecretArea = "15",
	CatalogueViewPermanentEventStore = "16",
	CatalogueViewNestingWorkshop = "17",
	CatalogueViewReturningSpirits = "18",
	CatalogueSettingsEverything = "19",
	CatalogueBackToStart = "20",
	CatalogueViewStart = "21",
	CatalogueViewRealm = "22",
	CatalogueViewSpirit = "23",
	CatalogueRealmEverything = "24",
	CatalogueEldersEverything = "25",
	CatalogueViewSeason = "26",
	CatalogueSetSeasonItems = "27",
	CatalogueSeasonEverything = "28",
	CatalogueViewEventYear = "29",
	CatalogueViewEvent = "30",
	CatalogueViewOffer1 = "31",
	CatalogueViewOffer2 = "32",
	CatalogueViewOffer3 = "33",
	CatalogueItemsEverything = "34",
	ChecklistDailyQuestsComplete = "35",
	ChecklistDailyQuestsShow = "36",
	ChecklistSeasonalCandlesComplete = "37",
	ChecklistEyeOfEdenComplete = "38",
	ChecklistShardEruptionsComplete = "39",
	ChecklistShardEruptionsShow = "40",
	ChecklistEventTicketsComplete = "41",
	DailyGuidesSetup = "42",
	DailyGuidesQuestsReorder = "43",
	DailyGuidesLocale = "44",
	DailyGuidesDistribute = "45",
	DataDelete = "46",
	/**
	 * Discord Delivery creates a message that uses this.
	 */
	FriendshipActionsContribute = "47",
	GuessSpiritOption1 = "48",
	GuessSpiritOption2 = "49",
	GuessSpiritOption3 = "50",
	GuessEventOption1 = "51",
	GuessEventOption2 = "52",
	GuessEventOption3 = "53",
	GuessEnd = "54",
	GuessTryAgain = "55",
	GuessLeaderboardBack = "56",
	GuessLeaderboardNext = "57",
	HeartHistoryBack = "58",
	HeartHistoryNext = "59",
	MeSetBio = "60",
	MeDeleteBio = "61",
	MeDeleteAvatar = "62",
	MeDeleteBanner = "63",
	MeSetBioModal = "64",
	MeSetBioModalBio = "65",
	NotificationsSetup = "66",
	NotificationsSetupChannel = "67",
	NotificationsSetupRole = "68",
	NotificationsSetupOffset = "69",
	NotificationsViewSetup = "70",
	ScheduleViewDetailedBreakdown = "71",
	ScheduleViewOverview = "72",
	ScheduleDetailedBreakdownViewShardEruptions = "73",
	ScheduleDetailedBreakdownViewDailyGuides = "74",
	ScheduleDetailedBreakdownViewSpirit = "75",
	ScheduleDetailedBreakdownViewSpiritHistory = "76",
	ShardEruptionTodayToday = "77",
	ShardEruptionTodayBack = "78",
	ShardEruptionTodayNext = "79",
	ShardEruptionBrowse = "80",
	ShardEruptionBrowseDates1 = "81",
	ShardEruptionBrowseDates2 = "82",
	ShardEruptionBrowseDates3 = "83",
	ShardEruptionBrowseDates4 = "84",
	ShardEruptionBrowseDates5 = "85",
	ShardEruptionBrowseToday = "86",
	ShardEruptionBrowseBack = "87",
	ShardEruptionBrowseNext = "88",
	ShopSuggest = "89",
	ShopSuggestionModal = "90",
	ShopSuggestionModalSuggestion = "91",
	SkyProfileEdit = "92",
	SkyProfileViewReset = "93",
	SkyProfileExplorer1 = "94",
	SkyProfileExplorer2 = "95",
	SkyProfileExplorer3 = "96",
	SkyProfileExplorer4 = "97",
	SkyProfileExplorerBack = "98",
	SkyProfileExplorerNext = "99",
	SkyProfileExplorerViewLikes = "100",
	SkyProfileExplorerProfileBack = "101",
	SkyProfileExplorerProfileNext = "102",
	SkyProfileExplorerProfileLike = "103",
	SkyProfileViewExplorer = "104",
	SkyProfileExplorerProfileReport = "105",
	SkyProfileExplorerLikes1 = "106",
	SkyProfileExplorerLikes2 = "107",
	SkyProfileExplorerLikes3 = "108",
	SkyProfileExplorerLikes4 = "109",
	SkyProfileExplorerLikesBack = "110",
	SkyProfileExplorerLikesNext = "111",
	SkyProfileExplorerLikesProfileBack = "112",
	SkyProfileExplorerLikesProfileNext = "113",
	SkyProfileExplorerLikesProfileLike = "114",
	SkyProfileExplorerLikesProfileReport = "115",
	SkyProfileExplorerViewProfile = "116",
	SkyProfileExplorerLikesViewProfile = "117",
	SkyProfileExplorerConfirmReport = "118",
	SkyProfileReportModal = "119",
	SkyProfileReportModalReason = "120",
	SkyProfileNameModal = "121",
	SkyProfileNameModalName = "122",
	SkyProfileDescriptionModal = "123",
	SkyProfileDescriptionModalDescription = "124",
	SkyProfileWingedLight = "125",
	SkyProfileViewEdit = "126",
	SkyProfileHangoutModal = "127",
	SkyProfileHangoutModalHangout = "128",
	SkyProfileSeasons1 = "129",
	SkyProfileSeasons2 = "130",
	SkyProfilePlatforms = "131",
	SkyProfileReset = "132",
	SpiritsViewSpirit = "133",
	SpiritsHistoryBack = "134",
	SpiritsHistoryNext = "135",
	WelcomeChannel = "136",
	WelcomeMessage = "137",
	WelcomeMessageDelete = "138",
	WelcomeHugEdit = "139",
	WelcomeAccentColour = "140",
	WelcomeAccentColourDelete = "141",
	WelcomeAssetDelete = "142",
	WelcomeHugSend = "143",
	WelcomeMessageModal = "144",
	WelcomeMessageModalMessage = "145",
	WelcomeAccentColourModal = "146",
	WelcomeAccentColourModalAccentColour = "147",
	AboutIssueModalAttachments = "148",
	MeCustomiseMe = "149",
	MeCustomiseMeModal = "150",
	MeCustomiseMeModalBio = "151",
	MeCustomiseMeModalAvatar = "152",
	MeCustomiseMeModalBanner = "153",
	SkyProfileIconModal = "154",
	SkyProfileIconModalIcon = "155",
	SkyProfileBannerModal = "156",
	SkyProfileBannerModalBanner = "157",
	WelcomeEdit = "158",
	WelcomeEditModal = "159",
	WelcomeEditModalChannel = "160",
	WelcomeEditModalMessage = "161",
	WelcomeEditModalAccentColour = "162",
	WelcomeEditModalHug = "163",
	WelcomeEditModalAsset = "164",
}

export const SHARD_ERUPTION_DATES = [
	CustomId.ShardEruptionBrowseDates1,
	CustomId.ShardEruptionBrowseDates2,
	CustomId.ShardEruptionBrowseDates3,
	CustomId.ShardEruptionBrowseDates4,
	CustomId.ShardEruptionBrowseDates5,
] as const satisfies readonly CustomId[];

export const SKY_PROFILE_EXPLORERS = [
	CustomId.SkyProfileExplorer1,
	CustomId.SkyProfileExplorer2,
	CustomId.SkyProfileExplorer3,
	CustomId.SkyProfileExplorer4,
] as const satisfies readonly CustomId[];

export const SKY_PROFILE_EXPLORER_LIKES = [
	CustomId.SkyProfileExplorerLikes1,
	CustomId.SkyProfileExplorerLikes2,
	CustomId.SkyProfileExplorerLikes3,
	CustomId.SkyProfileExplorerLikes4,
] as const satisfies readonly CustomId[];
