import { emojis } from "@thatskyapplication/utility";
import { PRODUCTION } from "./constants.js";

export const {
	MISCELLANEOUS_EMOJIS,
	EMOTE_EMOJIS,
	STANCE_EMOJIS,
	CALL_EMOJIS,
	FRIEND_ACTION_EMOJIS,
	SEASON_EMOJIS,
	EVENT_EMOJIS,
	OUTFIT_EMOJIS,
	SHOE_EMOJIS,
	MASK_EMOJIS,
	FACE_ACCESSORY_EMOJIS,
	NECKLACE_EMOJIS,
	HAIR_EMOJIS,
	HAIR_ACCESSORY_EMOJIS,
	CAPE_EMOJIS,
	HELD_PROPS_EMOJIS,
	LARGE_PLACEABLE_PROPS_EMOJIS,
	SMALL_PLACEABLE_PROPS_EMOJIS,
} = emojis(PRODUCTION);
