import {
	type Emoji,
	FriendAction,
	SpiritCall,
	SpiritEmote,
	SpiritName,
	SpiritStance,
} from "@thatskyapplication/utility";
import { CALL_EMOJIS, EMOTE_EMOJIS, FRIEND_ACTION_EMOJIS, STANCE_EMOJIS } from "./emojis.js";

export const SPIRIT_SEASONAL_FRIENDSHIP_TREE_BUTTON_CUSTOM_ID =
	"SPIRIT_VIEW_SEASONAL_BUTTON_CUSTOM_ID" as const;

export const SpiritEmoteToEmoji = {
	[SpiritEmote.Sit]: EMOTE_EMOJIS.Sit,
	[SpiritEmote.Point]: EMOTE_EMOJIS.Point,
	[SpiritEmote.Come]: EMOTE_EMOJIS.Come,
	[SpiritEmote.NoThanks]: EMOTE_EMOJIS.NoThanks,
	[SpiritEmote.Welcome]: EMOTE_EMOJIS.Welcome,
	[SpiritEmote.Nod]: EMOTE_EMOJIS.Nod,
	[SpiritEmote.Scold]: EMOTE_EMOJIS.Scold,
	[SpiritEmote.Butterfly]: EMOTE_EMOJIS.Butterfly,
	[SpiritEmote.Clap]: EMOTE_EMOJIS.Clap,
	[SpiritEmote.Wave]: EMOTE_EMOJIS.Wave,
	[SpiritEmote.Laugh]: EMOTE_EMOJIS.Laugh,
	[SpiritEmote.Yawn]: EMOTE_EMOJIS.Yawn,
	[SpiritEmote.WipeBrow]: EMOTE_EMOJIS.WipeBrow,
	[SpiritEmote.Teamwork]: EMOTE_EMOJIS.Teamwork,
	[SpiritEmote.BlowKiss]: EMOTE_EMOJIS.BlowKiss,
	[SpiritEmote.Grateful]: EMOTE_EMOJIS.Grateful,
	[SpiritEmote.BellyScratch]: EMOTE_EMOJIS.BellyScratch,
	[SpiritEmote.Chuckle]: EMOTE_EMOJIS.Chuckle,
	[SpiritEmote.Shiver]: EMOTE_EMOJIS.Shiver,
	[SpiritEmote.HideAndSeek]: EMOTE_EMOJIS.HideAndSeek,
	[SpiritEmote.Angry]: EMOTE_EMOJIS.Angry,
	[SpiritEmote.Shy]: EMOTE_EMOJIS.Shy,
	[SpiritEmote.Shocked]: EMOTE_EMOJIS.Shocked,
	[SpiritEmote.Apologise]: EMOTE_EMOJIS.Apologise,
	[SpiritEmote.Crying]: EMOTE_EMOJIS.Crying,
	[SpiritEmote.Kabuki]: EMOTE_EMOJIS.Kabuki,
	[SpiritEmote.Shrug]: EMOTE_EMOJIS.Shrug,
	[SpiritEmote.Grumpy]: EMOTE_EMOJIS.Grumpy,
	[SpiritEmote.Peek]: EMOTE_EMOJIS.Peek,
	[SpiritEmote.Eww]: EMOTE_EMOJIS.Eww,
	[SpiritEmote.Facepalm]: EMOTE_EMOJIS.Facepalm,
	[SpiritEmote.Handstand]: EMOTE_EMOJIS.Handstand,
	[SpiritEmote.Backflip]: EMOTE_EMOJIS.Backflip,
	[SpiritEmote.Bow]: EMOTE_EMOJIS.Bow,
	[SpiritEmote.Cheer]: EMOTE_EMOJIS.Cheer,
	[SpiritEmote.Leap]: EMOTE_EMOJIS.Leap,
	[SpiritEmote.TripleAxel]: EMOTE_EMOJIS.TripleAxel,
	[SpiritEmote.Confetti]: EMOTE_EMOJIS.Confetti,
	[SpiritEmote.BoogieDance]: EMOTE_EMOJIS.BoogieDance,
	[SpiritEmote.SpinDance]: EMOTE_EMOJIS.SpinDance,
	[SpiritEmote.Juggle]: EMOTE_EMOJIS.Juggle,
	[SpiritEmote.CrabWalk]: EMOTE_EMOJIS.CrabWalk,
	[SpiritEmote.RallyCheer]: EMOTE_EMOJIS.RallyCheer,
	[SpiritEmote.SpinTrick]: EMOTE_EMOJIS.SpinTrick,
	[SpiritEmote.ShowDance]: EMOTE_EMOJIS.ShowDance,
	[SpiritEmote.Duck]: EMOTE_EMOJIS.Duck,
	[SpiritEmote.Faint]: EMOTE_EMOJIS.Faint,
	[SpiritEmote.Respect]: EMOTE_EMOJIS.Respect,
	[SpiritEmote.LookAround]: EMOTE_EMOJIS.LookAround,
	[SpiritEmote.Salute]: EMOTE_EMOJIS.Salute,
	[SpiritEmote.Acknowledge]: EMOTE_EMOJIS.Acknowledge,
	[SpiritEmote.KungFu]: EMOTE_EMOJIS.KungFu,
	[SpiritEmote.DontGo]: EMOTE_EMOJIS.DontGo,
	[SpiritEmote.Boo]: EMOTE_EMOJIS.Boo,
	[SpiritEmote.DustOff]: EMOTE_EMOJIS.DustOff,
	[SpiritEmote.ChestPound]: EMOTE_EMOJIS.ChestPound,
	[SpiritEmote.Marching]: EMOTE_EMOJIS.Marching,
	[SpiritEmote.Telekinesis]: EMOTE_EMOJIS.Telekinesis,
	[SpiritEmote.Float]: EMOTE_EMOJIS.Float,
	[SpiritEmote.Pray]: EMOTE_EMOJIS.Pray,
	[SpiritEmote.Yoga]: EMOTE_EMOJIS.Yoga,
	[SpiritEmote.Shush]: EMOTE_EMOJIS.Shush,
	[SpiritEmote.Sparkler]: EMOTE_EMOJIS.Sparkler,
	[SpiritEmote.Thinking]: EMOTE_EMOJIS.Thinking,
	[SpiritEmote.Doze]: EMOTE_EMOJIS.Doze,
	[SpiritEmote.Balance]: EMOTE_EMOJIS.Balance,
	[SpiritEmote.DeepBreath]: EMOTE_EMOJIS.DeepBreath,
	[SpiritEmote.Bubbles]: EMOTE_EMOJIS.Bubbles,
	[SpiritEmote.Beckon]: EMOTE_EMOJIS.Beckon,
	[SpiritEmote.Gloat]: EMOTE_EMOJIS.Gloat,
	[SpiritEmote.Stretch]: EMOTE_EMOJIS.Stretch,
	[SpiritEmote.Slouch]: EMOTE_EMOJIS.Slouch,
	[SpiritEmote.Sneeze]: EMOTE_EMOJIS.Sneeze,
	[SpiritEmote.HandRub]: EMOTE_EMOJIS.HandRub,
	[SpiritEmote.Voilà]: EMOTE_EMOJIS.Voilà,
	[SpiritEmote.Navigate]: EMOTE_EMOJIS.Navigate,
	[SpiritEmote.CalmDown]: EMOTE_EMOJIS.CalmDown,
	[SpiritEmote.EvilLaugh]: EMOTE_EMOJIS.EvilLaugh,
	[SpiritEmote.Ouch]: EMOTE_EMOJIS.Ouch,
	[SpiritEmote.Anxious]: EMOTE_EMOJIS.Anxious,
	[SpiritEmote.Headbob]: EMOTE_EMOJIS.Headbob,
	[SpiritEmote.Aww]: EMOTE_EMOJIS.Aww,
	[SpiritEmote.WavingLight]: EMOTE_EMOJIS.WavingLight,
	[SpiritEmote.RaiseTheRoof]: EMOTE_EMOJIS.RaiseTheRoof,
	[SpiritEmote.Twirl]: EMOTE_EMOJIS.Twirl,
	[SpiritEmote.RhythmicClap]: EMOTE_EMOJIS.RhythmicClap,
	[SpiritEmote.Conduct]: EMOTE_EMOJIS.Conduct,
	[SpiritEmote.SilentClap]: EMOTE_EMOJIS.SilentClap,
	[SpiritEmote.Skipping]: EMOTE_EMOJIS.Skipping,
	[SpiritEmote.Pleading]: EMOTE_EMOJIS.Pleading,
	[SpiritEmote.Tiptoeing]: EMOTE_EMOJIS.Tiptoeing,
	[SpiritEmote.Grieving]: EMOTE_EMOJIS.Grieving,
	[SpiritEmote.HackySack]: EMOTE_EMOJIS.HackySack,
	[SpiritEmote.Somersault]: EMOTE_EMOJIS.Somersault,
	[SpiritEmote.Moping]: EMOTE_EMOJIS.Moping,
	[SpiritEmote.PullUp]: EMOTE_EMOJIS.PullUp,
	[SpiritEmote.JollyDance]: EMOTE_EMOJIS.JollyDance,
	[SpiritEmote.BlindfoldBalancePose]: EMOTE_EMOJIS.BlindfoldBalancePose,
	[SpiritEmote.CureForMeDance]: EMOTE_EMOJIS.CureForMeDance,
	[SpiritEmote.Whistle]: EMOTE_EMOJIS.Whistle,
	[SpiritEmote.Flex]: EMOTE_EMOJIS.Flex,
	[SpiritEmote.FloatSpin]: EMOTE_EMOJIS.FloatSpin,
	[SpiritEmote.Read]: EMOTE_EMOJIS.Read,
	[SpiritEmote.Cartwheel]: EMOTE_EMOJIS.Cartwheel,
	[SpiritEmote.HypeDance]: EMOTE_EMOJIS.HypeDance,
	[SpiritEmote.HeartGesture]: EMOTE_EMOJIS.HeartGesture,
} as const satisfies Readonly<Record<SpiritEmote, Emoji>>;

export const SpiritStanceToEmoji = {
	[SpiritStance.Base]: STANCE_EMOJIS.Base,
	[SpiritStance.Courageous]: STANCE_EMOJIS.Courageous,
	[SpiritStance.Confident]: STANCE_EMOJIS.Confident,
	[SpiritStance.Sneaky]: STANCE_EMOJIS.Sneaky,
	[SpiritStance.Proud]: STANCE_EMOJIS.Proud,
	[SpiritStance.Polite]: STANCE_EMOJIS.Polite,
	[SpiritStance.Sassy]: STANCE_EMOJIS.Sassy,
	[SpiritStance.Laidback]: STANCE_EMOJIS.Laidback,
	[SpiritStance.Wise]: STANCE_EMOJIS.Wise,
	[SpiritStance.Timid]: STANCE_EMOJIS.Timid,
	[SpiritStance.Tinker]: STANCE_EMOJIS.Tinker,
	[SpiritStance.Injured]: STANCE_EMOJIS.Injured,
} as const satisfies Readonly<Record<SpiritStance, Emoji>>;

export const SpiritCallToEmoji = {
	[SpiritCall.Base]: CALL_EMOJIS.Base,
	[SpiritCall.Bird]: CALL_EMOJIS.Bird,
	[SpiritCall.Whale]: CALL_EMOJIS.Whale,
	[SpiritCall.Manta]: CALL_EMOJIS.Manta,
	[SpiritCall.CosmicManta]: CALL_EMOJIS.CosmicManta,
	[SpiritCall.Crab]: CALL_EMOJIS.Crab,
	[SpiritCall.Jellyfish]: CALL_EMOJIS.Jellyfish,
	[SpiritCall.BabyManta]: CALL_EMOJIS.BabyManta,
	[SpiritCall.Nightbird]: CALL_EMOJIS.Nightbird,
} as const satisfies Readonly<
	Record<Exclude<SpiritCall, SpiritCall.KizunaAI | SpiritCall.Journey | SpiritCall.Ninny>, Emoji>
>;

export const FriendActionToEmoji = {
	[FriendAction.HoldHand]: FRIEND_ACTION_EMOJIS.HoldHand,
	[FriendAction.HighFive]: FRIEND_ACTION_EMOJIS.HighFive,
	[FriendAction.Hug]: FRIEND_ACTION_EMOJIS.Hug,
	[FriendAction.FistBump]: FRIEND_ACTION_EMOJIS.FistBump,
	[FriendAction.DoubleFive]: FRIEND_ACTION_EMOJIS.DoubleFive,
	[FriendAction.HairTousle]: FRIEND_ACTION_EMOJIS.HairTousle,
	[FriendAction.Carry]: FRIEND_ACTION_EMOJIS.Carry,
	[FriendAction.PlayFight]: FRIEND_ACTION_EMOJIS.PlayFight,
	[FriendAction.Bearhug]: FRIEND_ACTION_EMOJIS.Bearhug,
	[FriendAction.Handshake]: FRIEND_ACTION_EMOJIS.Handshake,
	[FriendAction.DuetDance]: FRIEND_ACTION_EMOJIS.DuetDance,
	[FriendAction.SideHug]: FRIEND_ACTION_EMOJIS.SideHug,
	[FriendAction.CradleCarry]: FRIEND_ACTION_EMOJIS.CradleCarry,
	[FriendAction.DuetBow]: FRIEND_ACTION_EMOJIS.DuetBow,
} as const satisfies Readonly<Record<FriendAction, Emoji>>;

export const QUEST_SPIRITS = [
	SpiritName.ButterflyCharmer,
	SpiritName.ApplaudingBellmaker,
	SpiritName.WavingBellmaker,
	SpiritName.SlumberingShipwright,
	SpiritName.LaughingLightCatcher,
	SpiritName.BirdWhisperer,
	SpiritName.ExhaustedDockWorker,
	SpiritName.CeremonialWorshiper,
	SpiritName.ShiveringTrailblazer,
	SpiritName.BlushingProspector,
	SpiritName.HideNSeekPioneer,
	SpiritName.PoutyPorter,
	SpiritName.DismayedHunter,
	SpiritName.ApologeticLumberjack,
	SpiritName.TearfulLightMiner,
	SpiritName.WhaleWhisperer,
	SpiritName.ConfidentSightseer,
	SpiritName.HandstandingThrillseeker,
	SpiritName.MantaWhisperer,
	SpiritName.BackflippingChampion,
	SpiritName.CheerfulSpectator,
	SpiritName.BowingMedalist,
	SpiritName.ProudVictor,
	SpiritName.FrightenedRefugee,
	SpiritName.FaintingWarrior,
	SpiritName.CourageousSoldier,
	SpiritName.StealthySurvivor,
	SpiritName.SalutingCaptain,
	SpiritName.LookoutScout,
	SpiritName.PrayingAcolyte,
	SpiritName.LevitatingAdept,
	SpiritName.PoliteScholar,
	SpiritName.MemoryWhisperer,
	SpiritName.MeditatingMonastic,
	SpiritName.StretchingGuru,
	SpiritName.ProvokingPerformer,
	SpiritName.LeapingDancer,
	SpiritName.SalutingProtector,
	SpiritName.GreetingShaman,
	SpiritName.DoublefiveLightCatcher,
	SpiritName.LaidbackPioneer,
	SpiritName.TwirlingChampion,
	SpiritName.CrabWhisperer,
	SpiritName.ShushingLightScholar,
	SpiritName.ConfettiCousin,
	SpiritName.HairtousleTeen,
	SpiritName.SparklerParent,
	SpiritName.PleafulParent,
	SpiritName.WiseGrandparent,
	SpiritName.FestivalSpinDancer,
	SpiritName.AdmiringActor,
	SpiritName.TroupeJuggler,
	SpiritName.RespectfulPianist,
	SpiritName.ThoughtfulDirector,
	SpiritName.NoddingMuralist,
	SpiritName.IndifferentAlchemist,
	SpiritName.CrabWalker,
	SpiritName.ScarecrowFarmer,
	SpiritName.SnoozingCarpenter,
	SpiritName.PlayfightingHerbalist,
	SpiritName.JellyWhisperer,
	SpiritName.TimidBookworm,
	SpiritName.RallyingThrillseeker,
	SpiritName.HikingGrouch,
	SpiritName.GratefulShellCollector,
	SpiritName.ChillSunbather,
	SpiritName.SpinningMentor,
	SpiritName.DancingPerformer,
	SpiritName.PeekingPostman,
	SpiritName.BearhugHermit,
	SpiritName.BaffledBotanist,
	SpiritName.ScoldingStudent,
	SpiritName.ScaredyCadet,
	SpiritName.MarchingAdventurer,
	SpiritName.ChucklingScout,
	SpiritName.DaydreamForester,
] as const satisfies Readonly<SpiritName[]>;

export type QuestSpirits = (typeof QUEST_SPIRITS)[number];
