root: true
parser: "@typescript-eslint/parser"
env:
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
plugins:
  - "@typescript-eslint"
  - import
reportUnusedDisableDirectives: true
rules:
  no-multiple-empty-lines:
    - 2
    - max: 1
      maxEOF: 0
      maxBOF: 0
  no-restricted-globals:
    - 2
    - Buffer
    - process
    - setImmediate
    - setInterval
    - setTimeout
    - clearImmediate
    - clearInterval
    - clearTimeout
  "@typescript-eslint/comma-dangle": 2
  "@typescript-eslint/explicit-function-return-type":
    - 2
    - allowExpressions: true
  "@typescript-eslint/explicit-module-boundary-types": 0
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/no-non-null-assertion": 0
  "@typescript-eslint/semi": 2
  "@typescript-eslint/member-delimiter-style":
    - 2
    - singleline:
        delimiter: comma
        requireLast: false
  "@typescript-eslint/quotes":
    - 2
    - double
    - avoidEscape: true
  import/first: 2
  import/newline-after-import: 2
  import/no-duplicates: 2
  import/order:
    - 2
    - groups:
        - builtin
        - external
        - internal
        - index
        - sibling
        - parent
      alphabetize:
        order: asc
