FROM alpine:3

RUN apk add --no-cache \
    postgresql16-client \
    aws-cli \
    bash

# Copy and set up the backup script.
COPY backup.sh /usr/local/bin/backup.sh
RUN chmod +x /usr/local/bin/backup.sh

# Set the backup script as the container's entry point.
CMD ["/usr/local/bin/backup.sh"]
