# fly.toml app configuration file generated for caelus on 2023-04-25T16:12:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "caelus"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = 5
