import { dailyGuidesQuestRoute } from "./routes.js";

export interface DailyGuidesPacket {
	quest1: number | null;
	quest2: number | null;
	quest3: number | null;
	quest4: number | null;
	travelling_rock: string | null;
	last_updated_user_id: string;
	last_updated_at: Date;
}

export const DailyQuest = {
	Collect30PiecesOfLight: 0,
	Light20Candles: 1,
	ForgeACandle: 2,
	Melt10Darkness: 3,
	BowAtAPlayer: 4,
	FollowAFriend: 5,
	HugAFriend: 6,
	WaveToAFriend: 7,
	HoldAFriendsHand: 8,
	SendAGiftToAFriend: 9,
	MakeANewAcquaintance: 10,
	HighFiveAFriend: 11,
	UseAnExpressionNearAFriend: 12,
	SitOnABenchWithAStranger: 13,
	RechargeFromAJellyfish: 14,
	RechargeFromALightBloom: 15,
	RideWithAManta: 16,
	ReliveASpiritsMemories: 17,
	ReliveASpiritsMemoriesInDaylightPrairie: 18,
	ReliveASpiritsMemoriesInHiddenForest: 19,
	ReliveASpiritsMemoriesInValleyOfTriumph: 20,
	ReliveASpiritsMemoriesInGoldenWasteland: 21,
	ReliveASpiritsMemoriesInVaultOfKnowledge: 22,
	FaceTheDarkDragon: 23,
	KnockOver5DarkCrabs: 24,
	CatchTheLightInTheDaylightPrairie: 25,
	CatchTheLightInTheHiddenForest: 26,
	CatchTheLightInTheValleyOfTriumph: 27,
	CatchTheLightInTheGoldenWasteland: 28,
	CatchTheLightInTheVaultOfKnowledge: 29,
	VisitTheCosyHideoutInTheDaylightPrairie: 30,
	VisitTheAncestorsTableOfBelongingInTheHiddenForest: 31,
	VisitTheHotSpringInTheValleyOfTriumph: 32,
	VisitTheBonfireAtTheGoldenWasteland: 33,
	AdmireTheSaplingInTheDaylightPrairie: 34,
	AdmireTheSaplingInTheHiddenForest: 35,
	AdmireTheSaplingInTheValleyOfTriumph: 36,
	AdmireTheSaplingInTheGoldenWasteland: 37,
	AdmireTheSaplingInTheVaultOfKnowledge: 38,
	VisitThePollutedGeyser: 39,
	RidTheSanctuaryVortexOfDarkness: 40,
	FindTheCandlesAtTheEndOfTheRainbowInTheDaylightPrairie: 41,
	FindTheCandlesAtTheEndOfTheRainbowInTheHiddenForest: 42,
	FindTheCandlesAtTheEndOfTheRainbowInTheValleyOfTriumph: 43,
	FindTheCandlesAtTheEndOfTheRainbowInTheGoldenWasteland: 44,
	FindTheCandlesAtTheEndOfTheRainbowInTheVaultOfKnowledge: 45,
	AdmireTheRainbowInTheSanctuaryIslands: 46,
	AdmireTheRainbowInTheWindPaths: 47,
	AdmireTheRainbowInTheHermitValley: 48,
	AdmireTheRainbowInTheTreasureReef: 49,
	AdmireTheRainbowInTheStarlightDesert: 50,
	MeditateAtTheBirdNest: 51,
	MeditateInTheButterflyFields: 52,
	MeditateAtTheSanctuaryIslands: 53,
	MeditateInTheCave: 54,
	MeditateByTheKoiPond: 55,
	MeditateAtTheForestClearing: 56,
	MeditateAtTheForestBrook: 57,
	MeditateAtTheElevatedClearing: 58,
	MeditateAtTheForestEnd: 59,
	MeditateAtTheBoneyard: 60,
	MeditateByTheIceRink: 61,
	MeditateAboveTheCitadelsArch: 62,
	MeditateHighAboveTheCitadel: 63,
	MeditateAtTheColiseum: 64,
	MeditateInTheBrokenTemple: 65,
	MeditateInTheForgottenArk: 66,
	MeditateInTheGraveyard: 67,
	MeditateOnTheBoat: 68,
	MeditateOnTheBattlefield: 69,
	MeditateAtTheVaultEntrance: 70,
	MeditateInTheVaultSecondFloor: 71,
	MeditateAtTheVaultSummit: 72,
	CollectGreenLight: 73,
	CollectOrangeLight: 74,
	CollectBlueLight: 75,
	CollectRedLight: 76,
	CollectPurpleLight: 77,
	PractiseWithTheSkater: 78,
	RaceDownTheSlopesWithTheSkater: 79,
	RaceDownTheMountainWithTheSkater: 80,
	RehearseForAPerformanceWithTheSkater: 81,
	CompleteTheHoopScavengerHunt: 82,
	ReliveTheButterflyCharmer: 83,
	ReliveTheApplaudingBellmaker: 84,
	ReliveTheWavingBellmaker: 85,
	ReliveTheSlumberingShipwright: 86,
	ReliveTheLaughingLightCatcher: 87,
	ReliveTheBirdWhisperer: 88,
	ReliveTheExhaustedDockWorker: 89,
	ReliveTheShiveringTrailblazer: 90,
	ReliveTheBlushingProspector: 91,
	ReliveTheHideNSeekPioneer: 92,
	ReliveThePoutyPorter: 93,
	ReliveTheDismayedHunter: 94,
	ReliveTheApologeticLumberjack: 95,
	ReliveTheTearfulLightMiner: 96,
	ReliveTheWhaleWhisperer: 97,
	ReliveTheConfidentSightseer: 98,
	ReliveTheHandstandingThrillseeker: 99,
	ReliveTheMantaWhisperer: 100,
	ReliveTheBackflippingChampion: 101,
	ReliveTheCheerfulSpectator: 102,
	ReliveTheBowingMedalist: 103,
	ReliveTheProudVictor: 104,
	ReliveTheFrightenedRefugee: 105,
	ReliveTheFaintingWarrior: 106,
	ReliveTheCourageousSoldier: 107,
	ReliveTheStealthySurvivor: 108,
	ReliveTheSalutingCaptain: 109,
	ReliveTheLookoutScout: 110,
	ReliveThePrayingAcolyte: 111,
	ReliveTheLevitatingAdept: 112,
	ReliveThePoliteScholar: 113,
	ReliveTheMemoryWhisperer: 114,
	ReliveTheMeditatingMonastic: 115,
	ReliveTheStretchingGuru: 116,
	ReliveTheProvokingPerformer: 117,
	ReliveTheLeapingDancer: 118,
	ReliveTheSalutingProtector: 119,
	ReliveTheGreetingShaman: 120,
	ReliveTheDoublefiveLightCatcher: 121,
	ReliveTheLaidbackPioneer: 122,
	ReliveTheTwirlingChampion: 123,
	ReliveTheCrabWhisperer: 124,
	ReliveTheShushingLightScholar: 125,
	ReliveTheConfettiCousin: 126,
	ReliveTheHairtousleTeen: 127,
	ReliveTheSparklerParent: 128,
	ReliveThePleafulParent: 129,
	ReliveTheWiseGrandparent: 130,
	ReliveTheFestivalSpinDancer: 131,
	ReliveTheAdmiringActor: 132,
	ReliveTheTroupeJuggler: 133,
	ReliveTheRespectfulPianist: 134,
	ReliveTheThoughtfulDirector: 135,
	ReliveTheNoddingMuralist: 136,
	ReliveTheIndifferentAlchemist: 137,
	ReliveTheCrabWalker: 138,
	ReliveTheScarecrowFarmer: 139,
	ReliveTheSnoozingCarpenter: 140,
	ReliveThePlayfightingHerbalist: 141,
	ReliveTheJellyWhisperer: 142,
	ReliveTheTimidBookworm: 143,
	ReliveTheRallyingThrillseeker: 144,
	ReliveTheHikingGrouch: 145,
	ReliveTheGratefulShellCollector: 146,
	ReliveTheChillSunbather: 147,
	ReliveTheSpinningMentor: 148,
	ReliveTheDancingPerformer: 149,
	ReliveThePeekingPostman: 150,
	ReliveTheBearhugHermit: 151,
	ReliveTheBaffledBotanist: 152,
	ReliveTheScoldingStudent: 153,
	ReliveTheScaredyCadet: 154,
	ReliveTheMarchingAdventurer: 155,
	ReliveTheChucklingScout: 156,
	ReliveTheDaydreamForester: 157,
	VisitAShardOfDarknessFallenToTheKingdomOfSky: 158,
	TakeASelfieWithHikingGrouchInPrairiePeaks: 159,
	TakeASelfieWithCrabWhispererInPrairiePeaks: 160,
	TakeASelfieWithCacklingCannoneerInPrairiePeaks: 161,
	TakeASelfieWithTroupeGreeterInPrairiePeaks: 162,
	MeetCinnamorollOnAHillInAviaryVillage: 163,
	SmellFlowersWithCinnamorollInAviaryVillage: 164,
	FindCinnamorollPeekingAroundAviaryVillage: 165,
	WakeUpCinnamorollInAviaryVillage: 166,
	FlyUpToTheTowerWithCinnamorollInAviaryVillage: 167,
	SplashInTheWaterWithCinnamorollInAviaryVillage: 168,
	PlayAnyTournamentSport: 169,
	MeetUpWithModestDancerInVillageOfDreams: 170,
	ForgetfulStorytellerNeedsHelpWithSomethingInVillageOfDreams: 171,
	MeetUpWithFranticStagehandInVillageTheatre: 172,
	MellowMusicianNeedsHelpWithSomethingInVillageTheatre: 173,
	ChangeYourHairstyle: 174,
	ChangeYourNecklace: 175,
	ChangeYourProp: 176,
	ChangeYourMask: 177,
	ChangeYourCape: 178,
	ChangeYourOutfit: 179,
	ViewASharedMemoryAtAStyleRunwayShrine: 180,
	RecordASharedMemoryAtAStyleRunwayShrine: 181,
	MeetUpWithCacklingCannoneerInTreasureReef: 182,
	MeetUpWithAnxiousAnglerInTreasureReef: 183,
	MeetUpWithMellowMusicianInVillageOfDreams: 184,
	MeetUpWithAnxiousAnglerInGoldenWasteland: 185,
	MeetUpWithAnxiousAnglerInCrabFields: 186,
	MeetUpWithCeasingCommodoreInTreasureReef: 187,
	MeetUpWithBlushingProspectorInForestBrook: 188,
	MeetUpWithShiveringTrailblazerInForestBrook: 189,
	MeetUpWithCacklingCannoneerInGraveyard: 190,
	MeetUpWithHideNSeekPioneerInBoneyard: 191,
	MeetUpWithHideNSeekPioneerInElevatedClearing: 192,
	MeetUpWithBumblingBoatswainInForgottenArk: 193,
	MeetUpWithHideNSeekPioneerInHiddenForest: 194,
	MeetUpWithCacklingCannoneerInForgottenArk: 195,
	MeetUpWithApologeticLumberjackInBoneyard: 196,
	MeetUpWithCeasingCommodoreInForgottenArk: 197,
	MeetUpWithJollyGeologistInPrairiePeaks: 198,
	MeetUpWithDismayedHunterInBoneyard: 199,
	MeetUpWithWhaleWhispererInBoneyard: 200,
	MeetUpWithAsceticMonkInSanctuaryIslands: 201,
	MeetUpWithNightbirdWhispererInSanctuaryIslands: 202,
	MeetUpWithJollyGeologistInSanctuaryIslands: 203,
	MeetUpWithAsceticMonkInPrairieVillage: 204,
	MeetUpWithNightbirdWhispererInPrairieVillage: 205,
	HelpAnxiousAnglerOrScoldingStudentFindTreasureInStarlightDesert: 206,
	HelpCacklingCannoneerOrChucklingScoutFindTreasureInSanctuaryIslands: 207,
	HelpTheBumblingBoatswainOrTheAssemblyGuideFindTreasureInHiddenForest: 208,
	HelpCeasingCommodoreOrDaydreamForesterFindTreasureInVillageOfDreams: 209,
	HelpTheAnxiousAnglerOrTheScoldingStudentFindTreasureInTreasureReef: 210,
	HelpTheCacklingCannoneerOrTheChucklingScoutFindTreasureInStarlightDesert: 211,
	HelpTheBumblingBoatswainOrTheAssemblyGuideFindTreasureInSanctuaryIslands: 212,
	HelpTheCeasingCommodoreOrTheDaydreamForesterFindTreasureInHiddenForest: 213,
	HelpTheAnxiousAnglerOrTheScoldingStudentFindTreasureInVillageOfDreams: 214,
	HelpTheCacklingCannoneerOrTheChucklingScoutFindTreasureInTreasureReef: 215,
	HelpTheBumblingBoatswainOrTheAssemblyGuideFindTreasureInStarlightDesert: 216,
	HelpTheCeasingCommodoreOrTheDaydreamForesterFindTreasureInSanctuaryIslands: 217,
	HelpTheAnxiousAnglerOrTheScoldingStudentFindTreasureInHiddenForest: 218,
	HelpTheCacklingCannoneerOrTheChucklingScoutFindTreasureInVillageOfDreams: 219,
	MeetUpWithPleadingChildInRepositoryOfRefuge: 220,
	MeetUpWithAsceticMonkInPrairiePeaks: 221,
	MeetUpWithReassuringRangerInPrairiePeaks: 222,
	MeetUpWithBlushingProspectorInValleyOfTriumph: 223,
	InvestigateABlueBirdSightingInTheIceRink: 224,
	InvestigateABlueBirdSightingInTheVaultRepository: 225,
	InvestigateABlueBirdSightingInVillageTheatre: 226,
	InvestigateABlueBirdSightingInTheForestClearing: 227,
	FindAClueOfTheBlueBirdsWhereaboutsInTheIceRink: 228,
	FindAClueOfTheBlueBirdsWhereaboutsInTheVaultRepository: 229,
	FindAClueOfTheBlueBirdsWhereaboutsInVillageTheatre: 230,
	FindAClueOfTheBlueBirdsWhereaboutsInTheForestClearing: 231,
	MeetUpWithBumblingBoatswainInTreasureReef: 232,
	MeetUpWithTalentedBuilderInBirdNest: 233,
	MeetUpWithTinkeringChimesmithInBirdNest: 234,
	MeetUpWithLightWhispererInBirdNest: 235,
	MeetUpWithLivelyNavigatorInBirdNest: 236,
	PickUpACrab: 237,
	AdmireSharedSpacesAtTheBrokenBellTowerInAviaryVillageForAShortWhile: 238,
	MeetUpWithGratefulShellCollectorInAviaryVillage: 239,
	MeetUpWithSparklerParentInAviaryVillage: 240,
	MeetUpWithAsceticMonkInAviaryVillage: 241,
	AdmireSharedSpacesWithApplaudingBellmaker: 242,
	AdmireSharedSpacesWithDaydreamForester: 243,
	AdmireSharedSpacesWithBearhugHermit: 244,
	AdmireSharedSpacesWithBumblingBoatswain: 245,
	MeetUpWithFlightGuideInPrairieVillage: 246,
	MeetUpWithLaughingLightCatcherInValleyOfTriumph: 247,
	MeetUpWithCourageousSoldierInValleyOfTriumph: 248,
	MeetUpWithFlightGuideInPrairieTemple: 249,
	MeetUpWithBackflippingChampionInValleyOfTriumph: 250,
	HelpThePrayingAcolyteArchiveSummerIntheArchives: 251,
	MeetUpWithThoughtfulDirectorInVaultOfKnowledge: 252,
	MeetUpWithApplaudingBellmakerInDaylightPrairie: 253,
	MeetUpWithFestivalSpinDancerInForestBrook: 254,
	MeetUpWithAdmiringActorInBirdNest: 255,
	MeetUpWithTroupeJugglerInGoldenWasteland: 256,
	MeetUpWithThoughtfulDirectorInRepositoryOfRefuge: 257,
	CatchThe3LightsDuringTheValleysSlidingRace: 258,
	InviteASeasonOfMigrationSpiritToAdventureWithYouToday: 259,
	MeetUpWithTumblingTroublemakerInPrairieCave: 260,
	UseExpressionsWithPlayers: 261,
	CatchThe3LightsInTheForestBrook: 262,
	CatchThe3LightsInThePrairiesBirdNest: 263,
	CatchThe3LightsInPrairieVillage: 264,
	CatchThe3LightsInTheWastelandsGraveyard: 265,
	CatchThe3LightsUnderTheSeaInTreasureReef: 266,
	CatchThe3LightsOnTheVaultsFourthFloor: 267,
	CatchThe3LightsInTheVaultsRepositoryOfRefuge: 268,
	CatchThe3LightsInTheBigTreehouse: 269,
	CatchThe3LightsInTheValleysCitadel: 270,
	RideAGiantMantaInSanctuaryIslands: 271,
	AdmireSharedSpacesWithTalentedBuilder: 272,
	FlyWithManyButterfliesInButterflyFields: 273,
	MeetUpWithMelancholyMopeInForestBrook: 274,
	FinishNatsBroomstickRaceInCacklingCrab: 275,
	HelpAustinCollect5CrabsInTheBasementOfTheCacklingCrab: 276,
	HelpSkidmoreFireTheCannons3TimesInTheCacklingCrab: 277,
	HopIntoYoshisCauldronBrewInTheCacklingCrab: 278,
	MeetUpWithOddballOutcastInHiddenForest: 279,
} as const satisfies Readonly<Record<string, number>>;

export const DAILY_QUEST_VALUES = Object.values(DailyQuest);
export type DailyQuests = (typeof DAILY_QUEST_VALUES)[number];

export function isDailyQuest(dailyQuest: number): dailyQuest is DailyQuests {
	return DAILY_QUEST_VALUES.includes(dailyQuest as DailyQuests);
}

export const DailyQuestToInfographicURL = {
	[DailyQuest.Collect30PiecesOfLight]: null,
	[DailyQuest.Light20Candles]: null,
	[DailyQuest.ForgeACandle]: null,
	[DailyQuest.Melt10Darkness]: null,
	[DailyQuest.BowAtAPlayer]: dailyGuidesQuestRoute("social/bow_at_a_player"),
	[DailyQuest.FollowAFriend]: dailyGuidesQuestRoute("social/follow_a_friend"),
	[DailyQuest.HugAFriend]: dailyGuidesQuestRoute("social/hug_a_friend"),
	[DailyQuest.WaveToAFriend]: dailyGuidesQuestRoute("social/wave_to_a_friend"),
	[DailyQuest.HoldAFriendsHand]: dailyGuidesQuestRoute("social/hold_a_friends_hand"),
	[DailyQuest.SendAGiftToAFriend]: dailyGuidesQuestRoute("social/send_a_gift_to_a_friend"),
	[DailyQuest.MakeANewAcquaintance]: dailyGuidesQuestRoute("social/make_a_new_acquaintance"),
	[DailyQuest.HighFiveAFriend]: dailyGuidesQuestRoute("social/high_five_a_friend"),
	[DailyQuest.UseAnExpressionNearAFriend]: dailyGuidesQuestRoute(
		"social/use_an_expression_near_a_friend",
	),
	[DailyQuest.SitOnABenchWithAStranger]: dailyGuidesQuestRoute(
		"social/sit_on_a_bench_with_a_stranger",
	),
	[DailyQuest.RechargeFromAJellyfish]: dailyGuidesQuestRoute(
		"miscellaneous/recharge_from_a_jellyfish",
	),
	[DailyQuest.RechargeFromALightBloom]: dailyGuidesQuestRoute(
		"miscellaneous/recharge_from_a_light_bloom",
	),
	[DailyQuest.RideWithAManta]: dailyGuidesQuestRoute("miscellaneous/ride_a_manta"),
	[DailyQuest.ReliveASpiritsMemories]: dailyGuidesQuestRoute(
		"miscellaneous/relive_a_spirits_memories",
	),
	[DailyQuest.ReliveASpiritsMemoriesInDaylightPrairie]: dailyGuidesQuestRoute(
		"miscellaneous/relive_a_spirits_memories",
	),
	[DailyQuest.ReliveASpiritsMemoriesInHiddenForest]: dailyGuidesQuestRoute(
		"miscellaneous/relive_a_spirits_memories",
	),
	[DailyQuest.ReliveASpiritsMemoriesInValleyOfTriumph]: dailyGuidesQuestRoute(
		"miscellaneous/relive_a_spirits_memories",
	),
	[DailyQuest.ReliveASpiritsMemoriesInGoldenWasteland]: dailyGuidesQuestRoute(
		"miscellaneous/relive_a_spirits_memories",
	),
	[DailyQuest.ReliveASpiritsMemoriesInVaultOfKnowledge]: dailyGuidesQuestRoute(
		"miscellaneous/relive_a_spirits_memories",
	),
	[DailyQuest.FaceTheDarkDragon]: dailyGuidesQuestRoute("miscellaneous/face_the_dark_dragon", true),
	[DailyQuest.KnockOver5DarkCrabs]: dailyGuidesQuestRoute("miscellaneous/knock_over_5_dark_crabs"),
	[DailyQuest.CatchTheLightInTheDaylightPrairie]: dailyGuidesQuestRoute(
		"catch_the_light/daylight_prairie",
	),
	[DailyQuest.CatchTheLightInTheHiddenForest]: dailyGuidesQuestRoute(
		"catch_the_light/hidden_forest",
	),
	[DailyQuest.CatchTheLightInTheValleyOfTriumph]: dailyGuidesQuestRoute(
		"catch_the_light/valley_of_triumph",
	),
	[DailyQuest.CatchTheLightInTheGoldenWasteland]: dailyGuidesQuestRoute(
		"catch_the_light/golden_wasteland",
	),
	[DailyQuest.CatchTheLightInTheVaultOfKnowledge]: dailyGuidesQuestRoute(
		"catch_the_light/vault_of_knowledge",
	),
	[DailyQuest.VisitTheCosyHideoutInTheDaylightPrairie]: dailyGuidesQuestRoute(
		"miscellaneous/visit_the_cosy_hideout",
	),
	[DailyQuest.VisitTheAncestorsTableOfBelongingInTheHiddenForest]: dailyGuidesQuestRoute(
		"miscellaneous/visit_the_ancestors_table_of_belonging",
	),
	[DailyQuest.VisitTheHotSpringInTheValleyOfTriumph]: dailyGuidesQuestRoute(
		"miscellaneous/visit_the_hot_spring",
	),
	[DailyQuest.VisitTheBonfireAtTheGoldenWasteland]: dailyGuidesQuestRoute(
		"miscellaneous/visit_the_bonfire",
	),
	[DailyQuest.AdmireTheSaplingInTheDaylightPrairie]: dailyGuidesQuestRoute(
		"days_of_bloom/daylight_prairie",
	),
	[DailyQuest.AdmireTheSaplingInTheHiddenForest]: dailyGuidesQuestRoute(
		"days_of_bloom/hidden_forest",
	),
	[DailyQuest.AdmireTheSaplingInTheValleyOfTriumph]: dailyGuidesQuestRoute(
		"days_of_bloom/valley_of_triumph",
	),
	[DailyQuest.AdmireTheSaplingInTheGoldenWasteland]: dailyGuidesQuestRoute(
		"days_of_bloom/golden_wasteland",
	),
	[DailyQuest.AdmireTheSaplingInTheVaultOfKnowledge]: dailyGuidesQuestRoute(
		"days_of_bloom/vault_of_knowledge",
	),
	[DailyQuest.VisitThePollutedGeyser]: dailyGuidesQuestRoute(
		"days_of_nature/visit_the_polluted_geyser",
	),
	[DailyQuest.RidTheSanctuaryVortexOfDarkness]: dailyGuidesQuestRoute(
		"days_of_nature/rid_the_sanctuary_vortex_of_darkness",
	),
	[DailyQuest.FindTheCandlesAtTheEndOfTheRainbowInTheDaylightPrairie]: dailyGuidesQuestRoute(
		"days_of_colour/find/daylight_prairie",
	),
	[DailyQuest.FindTheCandlesAtTheEndOfTheRainbowInTheHiddenForest]: dailyGuidesQuestRoute(
		"days_of_colour/find/hidden_forest",
	),
	[DailyQuest.FindTheCandlesAtTheEndOfTheRainbowInTheValleyOfTriumph]: dailyGuidesQuestRoute(
		"days_of_colour/find/valley_of_triumph",
	),
	[DailyQuest.FindTheCandlesAtTheEndOfTheRainbowInTheGoldenWasteland]: dailyGuidesQuestRoute(
		"days_of_colour/find/golden_wasteland",
	),
	[DailyQuest.FindTheCandlesAtTheEndOfTheRainbowInTheVaultOfKnowledge]: dailyGuidesQuestRoute(
		"days_of_colour/find/vault_of_knowledge",
	),
	[DailyQuest.AdmireTheRainbowInTheSanctuaryIslands]: dailyGuidesQuestRoute(
		"days_of_colour/admire/sanctuary_islands",
	),
	[DailyQuest.AdmireTheRainbowInTheWindPaths]: dailyGuidesQuestRoute(
		"days_of_colour/admire/wind_paths",
	),
	[DailyQuest.AdmireTheRainbowInTheHermitValley]: dailyGuidesQuestRoute(
		"days_of_colour/admire/hermit_valley",
	),
	[DailyQuest.AdmireTheRainbowInTheTreasureReef]: dailyGuidesQuestRoute(
		"days_of_colour/admire/treasure_reef",
	),
	[DailyQuest.AdmireTheRainbowInTheStarlightDesert]: dailyGuidesQuestRoute(
		"days_of_colour/admire/starlight_desert",
	),
	[DailyQuest.MeditateAtTheBirdNest]: dailyGuidesQuestRoute("season_of_gratitude/bird_nest"),
	[DailyQuest.MeditateInTheButterflyFields]: dailyGuidesQuestRoute(
		"season_of_gratitude/butterfly_fields",
	),
	[DailyQuest.MeditateAtTheSanctuaryIslands]: dailyGuidesQuestRoute(
		"season_of_gratitude/sanctuary_islands",
	),
	[DailyQuest.MeditateInTheCave]: dailyGuidesQuestRoute("season_of_gratitude/cave"),
	[DailyQuest.MeditateByTheKoiPond]: dailyGuidesQuestRoute("season_of_gratitude/koi_pond"),
	[DailyQuest.MeditateAtTheForestClearing]: dailyGuidesQuestRoute(
		"season_of_gratitude/forest_clearing",
	),
	[DailyQuest.MeditateAtTheForestBrook]: dailyGuidesQuestRoute("season_of_gratitude/forest_brook"),
	[DailyQuest.MeditateAtTheElevatedClearing]: dailyGuidesQuestRoute(
		"season_of_gratitude/elevated_clearing",
	),
	[DailyQuest.MeditateAtTheForestEnd]: dailyGuidesQuestRoute("season_of_gratitude/forest_end"),
	[DailyQuest.MeditateAtTheBoneyard]: dailyGuidesQuestRoute("season_of_gratitude/boneyard"),
	[DailyQuest.MeditateByTheIceRink]: dailyGuidesQuestRoute("season_of_gratitude/ice_rink"),
	[DailyQuest.MeditateAboveTheCitadelsArch]: dailyGuidesQuestRoute(
		"season_of_gratitude/citadel/arch",
	),
	[DailyQuest.MeditateHighAboveTheCitadel]: dailyGuidesQuestRoute(
		"season_of_gratitude/citadel/high_above",
	),
	[DailyQuest.MeditateAtTheColiseum]: dailyGuidesQuestRoute("season_of_gratitude/coliseum"),
	[DailyQuest.MeditateInTheBrokenTemple]: dailyGuidesQuestRoute(
		"season_of_gratitude/broken_temple",
	),
	[DailyQuest.MeditateInTheForgottenArk]: dailyGuidesQuestRoute(
		"season_of_gratitude/forgotten_ark",
	),
	[DailyQuest.MeditateInTheGraveyard]: dailyGuidesQuestRoute("season_of_gratitude/graveyard"),
	[DailyQuest.MeditateOnTheBoat]: dailyGuidesQuestRoute("season_of_gratitude/boat"),
	[DailyQuest.MeditateOnTheBattlefield]: dailyGuidesQuestRoute("season_of_gratitude/battlefield"),
	[DailyQuest.MeditateAtTheVaultEntrance]: dailyGuidesQuestRoute(
		"season_of_gratitude/vault_entrance",
	),
	[DailyQuest.MeditateInTheVaultSecondFloor]: dailyGuidesQuestRoute(
		"season_of_gratitude/vault_second_floor",
	),
	[DailyQuest.MeditateAtTheVaultSummit]: dailyGuidesQuestRoute("season_of_gratitude/vault_summit"),
	[DailyQuest.CollectGreenLight]: dailyGuidesQuestRoute(
		"season_of_enchantment/collect_green_light",
	),
	[DailyQuest.CollectOrangeLight]: dailyGuidesQuestRoute(
		"season_of_enchantment/collect_orange_light",
	),
	[DailyQuest.CollectBlueLight]: dailyGuidesQuestRoute("season_of_enchantment/collect_blue_light"),
	[DailyQuest.CollectRedLight]: dailyGuidesQuestRoute("season_of_enchantment/collect_red_light"),
	[DailyQuest.CollectPurpleLight]: dailyGuidesQuestRoute(
		"season_of_enchantment/collect_purple_light",
	),
	[DailyQuest.PractiseWithTheSkater]: dailyGuidesQuestRoute(
		"season_of_dreams/practise_with_the_skater",
	),
	[DailyQuest.RaceDownTheSlopesWithTheSkater]: dailyGuidesQuestRoute(
		"season_of_dreams/race_down_the_slopes_with_the_skater",
	),
	[DailyQuest.RaceDownTheMountainWithTheSkater]: dailyGuidesQuestRoute(
		"season_of_dreams/race_down_the_mountain_with_the_skater",
	),
	[DailyQuest.RehearseForAPerformanceWithTheSkater]: dailyGuidesQuestRoute(
		"season_of_dreams/rehearse_for_a_performance_with_the_skater",
	),
	[DailyQuest.CompleteTheHoopScavengerHunt]: dailyGuidesQuestRoute("season_of_assembly/hoop"),
	[DailyQuest.ReliveTheButterflyCharmer]: dailyGuidesQuestRoute("spirits/butterfly_charmer"),
	[DailyQuest.ReliveTheApplaudingBellmaker]: dailyGuidesQuestRoute("spirits/applauding_bellmaker"),
	[DailyQuest.ReliveTheWavingBellmaker]: dailyGuidesQuestRoute("spirits/waving_bellmaker"),
	[DailyQuest.ReliveTheSlumberingShipwright]: dailyGuidesQuestRoute(
		"spirits/slumbering_shipwright",
	),
	[DailyQuest.ReliveTheLaughingLightCatcher]: dailyGuidesQuestRoute(
		"spirits/laughing_light_catcher",
	),
	[DailyQuest.ReliveTheBirdWhisperer]: dailyGuidesQuestRoute("spirits/bird_whisperer"),
	[DailyQuest.ReliveTheExhaustedDockWorker]: dailyGuidesQuestRoute("spirits/exhausted_dock_worker"),
	[DailyQuest.ReliveTheShiveringTrailblazer]: dailyGuidesQuestRoute(
		"spirits/shivering_trailblazer",
	),
	[DailyQuest.ReliveTheBlushingProspector]: dailyGuidesQuestRoute("spirits/blushing_prospector"),
	[DailyQuest.ReliveTheHideNSeekPioneer]: dailyGuidesQuestRoute("spirits/hide_n_seek_pioneer"),
	[DailyQuest.ReliveThePoutyPorter]: dailyGuidesQuestRoute("spirits/pouty_porter"),
	[DailyQuest.ReliveTheDismayedHunter]: dailyGuidesQuestRoute("spirits/dismayed_hunter"),
	[DailyQuest.ReliveTheApologeticLumberjack]: dailyGuidesQuestRoute(
		"spirits/apologetic_lumberjack",
	),
	[DailyQuest.ReliveTheTearfulLightMiner]: dailyGuidesQuestRoute("spirits/tearful_light_miner"),
	[DailyQuest.ReliveTheWhaleWhisperer]: dailyGuidesQuestRoute("spirits/whale_whisperer"),
	[DailyQuest.ReliveTheConfidentSightseer]: dailyGuidesQuestRoute("spirits/confident_sightseer"),
	[DailyQuest.ReliveTheHandstandingThrillseeker]: dailyGuidesQuestRoute(
		"spirits/handstanding_thrillseeker",
	),
	[DailyQuest.ReliveTheMantaWhisperer]: dailyGuidesQuestRoute("spirits/manta_whisperer"),
	[DailyQuest.ReliveTheBackflippingChampion]: dailyGuidesQuestRoute(
		"spirits/backflipping_champion",
	),
	[DailyQuest.ReliveTheCheerfulSpectator]: dailyGuidesQuestRoute("spirits/cheerful_spectator"),
	[DailyQuest.ReliveTheBowingMedalist]: dailyGuidesQuestRoute("spirits/bowing_medalist"),
	[DailyQuest.ReliveTheProudVictor]: dailyGuidesQuestRoute("spirits/proud_victor"),
	[DailyQuest.ReliveTheFrightenedRefugee]: dailyGuidesQuestRoute("spirits/frightened_refugee"),
	[DailyQuest.ReliveTheFaintingWarrior]: dailyGuidesQuestRoute("spirits/fainting_warrior"),
	[DailyQuest.ReliveTheCourageousSoldier]: dailyGuidesQuestRoute("spirits/courageous_soldier"),
	[DailyQuest.ReliveTheStealthySurvivor]: dailyGuidesQuestRoute("spirits/stealthy_survivor"),
	[DailyQuest.ReliveTheSalutingCaptain]: dailyGuidesQuestRoute("spirits/saluting_captain"),
	[DailyQuest.ReliveTheLookoutScout]: dailyGuidesQuestRoute("spirits/lookout_scout"),
	[DailyQuest.ReliveThePrayingAcolyte]: dailyGuidesQuestRoute("spirits/praying_acolyte"),
	[DailyQuest.ReliveTheLevitatingAdept]: dailyGuidesQuestRoute("spirits/levitating_adept"),
	[DailyQuest.ReliveThePoliteScholar]: dailyGuidesQuestRoute("spirits/polite_scholar"),
	[DailyQuest.ReliveTheMemoryWhisperer]: dailyGuidesQuestRoute("spirits/memory_whisperer"),
	[DailyQuest.ReliveTheMeditatingMonastic]: dailyGuidesQuestRoute("spirits/meditating_monastic"),
	[DailyQuest.ReliveTheStretchingGuru]: dailyGuidesQuestRoute("spirits/stretching_guru"),
	[DailyQuest.ReliveTheProvokingPerformer]: dailyGuidesQuestRoute("spirits/provoking_performer"),
	[DailyQuest.ReliveTheLeapingDancer]: dailyGuidesQuestRoute("spirits/leaping_dancer"),
	[DailyQuest.ReliveTheSalutingProtector]: dailyGuidesQuestRoute("spirits/saluting_protector"),
	[DailyQuest.ReliveTheGreetingShaman]: dailyGuidesQuestRoute("spirits/greeting_shaman"),
	[DailyQuest.ReliveTheDoublefiveLightCatcher]: dailyGuidesQuestRoute(
		"spirits/doublefive_light_catcher",
	),
	[DailyQuest.ReliveTheLaidbackPioneer]: dailyGuidesQuestRoute("spirits/laidback_pioneer"),
	[DailyQuest.ReliveTheTwirlingChampion]: dailyGuidesQuestRoute("spirits/twirling_champion"),
	[DailyQuest.ReliveTheCrabWhisperer]: dailyGuidesQuestRoute("spirits/crab_whisperer"),
	[DailyQuest.ReliveTheShushingLightScholar]: dailyGuidesQuestRoute(
		"spirits/shushing_light_scholar",
	),
	[DailyQuest.ReliveTheConfettiCousin]: dailyGuidesQuestRoute("spirits/confetti_cousin"),
	[DailyQuest.ReliveTheHairtousleTeen]: dailyGuidesQuestRoute("spirits/hairtousle_teen"),
	[DailyQuest.ReliveTheSparklerParent]: dailyGuidesQuestRoute("spirits/sparkler_parent"),
	[DailyQuest.ReliveThePleafulParent]: dailyGuidesQuestRoute("spirits/pleaful_parent"),
	[DailyQuest.ReliveTheWiseGrandparent]: dailyGuidesQuestRoute("spirits/wise_grandparent"),
	[DailyQuest.ReliveTheFestivalSpinDancer]: dailyGuidesQuestRoute("spirits/festival_spin_dancer"),
	[DailyQuest.ReliveTheAdmiringActor]: dailyGuidesQuestRoute("spirits/admiring_actor"),
	[DailyQuest.ReliveTheTroupeJuggler]: dailyGuidesQuestRoute("spirits/troupe_juggler"),
	[DailyQuest.ReliveTheRespectfulPianist]: dailyGuidesQuestRoute("spirits/respectful_pianist"),
	[DailyQuest.ReliveTheThoughtfulDirector]: dailyGuidesQuestRoute("spirits/thoughtful_director"),
	[DailyQuest.ReliveTheNoddingMuralist]: dailyGuidesQuestRoute("spirits/nodding_muralist"),
	[DailyQuest.ReliveTheIndifferentAlchemist]: dailyGuidesQuestRoute(
		"spirits/indifferent_alchemist",
	),
	[DailyQuest.ReliveTheCrabWalker]: dailyGuidesQuestRoute("spirits/crab_walker"),
	[DailyQuest.ReliveTheScarecrowFarmer]: dailyGuidesQuestRoute("spirits/scarecrow_farmer"),
	[DailyQuest.ReliveTheSnoozingCarpenter]: dailyGuidesQuestRoute("spirits/snoozing_carpenter"),
	[DailyQuest.ReliveThePlayfightingHerbalist]: dailyGuidesQuestRoute(
		"spirits/playfighting_herbalist",
	),
	[DailyQuest.ReliveTheJellyWhisperer]: dailyGuidesQuestRoute("spirits/jelly_whisperer"),
	[DailyQuest.ReliveTheTimidBookworm]: dailyGuidesQuestRoute("spirits/timid_bookworm"),
	[DailyQuest.ReliveTheRallyingThrillseeker]: dailyGuidesQuestRoute(
		"spirits/rallying_thrillseeker",
	),
	[DailyQuest.ReliveTheHikingGrouch]: dailyGuidesQuestRoute("spirits/hiking_grouch"),
	[DailyQuest.ReliveTheGratefulShellCollector]: dailyGuidesQuestRoute(
		"spirits/grateful_shell_collector",
	),
	[DailyQuest.ReliveTheChillSunbather]: dailyGuidesQuestRoute("spirits/chill_sunbather"),
	[DailyQuest.ReliveTheSpinningMentor]: dailyGuidesQuestRoute("spirits/spinning_mentor"),
	[DailyQuest.ReliveTheDancingPerformer]: dailyGuidesQuestRoute("spirits/dancing_performer"),
	[DailyQuest.ReliveThePeekingPostman]: dailyGuidesQuestRoute("spirits/peeking_postman"),
	[DailyQuest.ReliveTheBearhugHermit]: dailyGuidesQuestRoute("spirits/bearhug_hermit"),
	[DailyQuest.ReliveTheBaffledBotanist]: dailyGuidesQuestRoute("spirits/baffled_botanist"),
	[DailyQuest.ReliveTheScoldingStudent]: dailyGuidesQuestRoute("spirits/scolding_student"),
	[DailyQuest.ReliveTheScaredyCadet]: dailyGuidesQuestRoute("spirits/scaredy_cadet"),
	[DailyQuest.ReliveTheMarchingAdventurer]: dailyGuidesQuestRoute("spirits/marching_adventurer"),
	[DailyQuest.ReliveTheChucklingScout]: dailyGuidesQuestRoute("spirits/chuckling_scout"),
	[DailyQuest.ReliveTheDaydreamForester]: dailyGuidesQuestRoute("spirits/daydream_forester"),
	[DailyQuest.VisitAShardOfDarknessFallenToTheKingdomOfSky]: null,
	[DailyQuest.TakeASelfieWithHikingGrouchInPrairiePeaks]: null,
	[DailyQuest.TakeASelfieWithCrabWhispererInPrairiePeaks]: null,
	[DailyQuest.TakeASelfieWithCacklingCannoneerInPrairiePeaks]: null,
	[DailyQuest.TakeASelfieWithTroupeGreeterInPrairiePeaks]: null,
	[DailyQuest.MeetCinnamorollOnAHillInAviaryVillage]: dailyGuidesQuestRoute(
		"sky_x_cinnamoroll_pop_up_cafe/meet_cinnamoroll_on_a_hill_in_aviary_village",
	),
	[DailyQuest.SmellFlowersWithCinnamorollInAviaryVillage]: dailyGuidesQuestRoute(
		"sky_x_cinnamoroll_pop_up_cafe/smell_flowers_with_cinnamoroll_in_aviary_village",
	),
	[DailyQuest.FindCinnamorollPeekingAroundAviaryVillage]: dailyGuidesQuestRoute(
		"sky_x_cinnamoroll_pop_up_cafe/find_cinnamoroll_peeking_around_aviary_village",
	),
	[DailyQuest.WakeUpCinnamorollInAviaryVillage]: dailyGuidesQuestRoute(
		"sky_x_cinnamoroll_pop_up_cafe/wake_up_cinnamoroll_in_aviary_village",
	),
	[DailyQuest.FlyUpToTheTowerWithCinnamorollInAviaryVillage]: dailyGuidesQuestRoute(
		"sky_x_cinnamoroll_pop_up_cafe/fly_up_to_the_tower_with_cinnamoroll_in_aviary_village",
	),
	[DailyQuest.SplashInTheWaterWithCinnamorollInAviaryVillage]: dailyGuidesQuestRoute(
		"sky_x_cinnamoroll_pop_up_cafe/splash_in_the_water_with_cinnamoroll_in_aviary_village",
	),
	[DailyQuest.PlayAnyTournamentSport]: null,
	[DailyQuest.MeetUpWithModestDancerInVillageOfDreams]: null,
	[DailyQuest.ForgetfulStorytellerNeedsHelpWithSomethingInVillageOfDreams]: null,
	[DailyQuest.MeetUpWithFranticStagehandInVillageTheatre]: null,
	[DailyQuest.MellowMusicianNeedsHelpWithSomethingInVillageTheatre]: null,
	[DailyQuest.ChangeYourHairstyle]: null,
	[DailyQuest.ChangeYourNecklace]: null,
	[DailyQuest.ChangeYourProp]: null,
	[DailyQuest.ChangeYourMask]: null,
	[DailyQuest.ChangeYourCape]: null,
	[DailyQuest.ChangeYourOutfit]: null,
	[DailyQuest.ViewASharedMemoryAtAStyleRunwayShrine]: null,
	[DailyQuest.RecordASharedMemoryAtAStyleRunwayShrine]: null,
	[DailyQuest.MeetUpWithCacklingCannoneerInTreasureReef]: null,
	[DailyQuest.MeetUpWithAnxiousAnglerInTreasureReef]: null,
	[DailyQuest.MeetUpWithMellowMusicianInVillageOfDreams]: null,
	[DailyQuest.MeetUpWithAnxiousAnglerInGoldenWasteland]: null,
	[DailyQuest.MeetUpWithAnxiousAnglerInCrabFields]: null,
	[DailyQuest.MeetUpWithCeasingCommodoreInTreasureReef]: null,
	[DailyQuest.MeetUpWithBlushingProspectorInForestBrook]: null,
	[DailyQuest.MeetUpWithShiveringTrailblazerInForestBrook]: null,
	[DailyQuest.MeetUpWithCacklingCannoneerInGraveyard]: null,
	[DailyQuest.MeetUpWithHideNSeekPioneerInBoneyard]: null,
	[DailyQuest.MeetUpWithHideNSeekPioneerInElevatedClearing]: null,
	[DailyQuest.MeetUpWithBumblingBoatswainInForgottenArk]: null,
	[DailyQuest.MeetUpWithHideNSeekPioneerInHiddenForest]: null,
	[DailyQuest.MeetUpWithCacklingCannoneerInForgottenArk]: null,
	[DailyQuest.MeetUpWithApologeticLumberjackInBoneyard]: null,
	[DailyQuest.MeetUpWithCeasingCommodoreInForgottenArk]: null,
	[DailyQuest.MeetUpWithJollyGeologistInPrairiePeaks]: null,
	[DailyQuest.MeetUpWithDismayedHunterInBoneyard]: null,
	[DailyQuest.MeetUpWithWhaleWhispererInBoneyard]: null,
	[DailyQuest.MeetUpWithAsceticMonkInSanctuaryIslands]: null,
	[DailyQuest.MeetUpWithNightbirdWhispererInSanctuaryIslands]: null,
	[DailyQuest.MeetUpWithJollyGeologistInSanctuaryIslands]: null,
	[DailyQuest.MeetUpWithAsceticMonkInPrairieVillage]: null,
	[DailyQuest.MeetUpWithNightbirdWhispererInPrairieVillage]: null,
	[DailyQuest.HelpAnxiousAnglerOrScoldingStudentFindTreasureInStarlightDesert]: null,
	[DailyQuest.HelpCacklingCannoneerOrChucklingScoutFindTreasureInSanctuaryIslands]: null,
	[DailyQuest.HelpTheBumblingBoatswainOrTheAssemblyGuideFindTreasureInHiddenForest]: null,
	[DailyQuest.HelpCeasingCommodoreOrDaydreamForesterFindTreasureInVillageOfDreams]: null,
	[DailyQuest.HelpTheAnxiousAnglerOrTheScoldingStudentFindTreasureInTreasureReef]: null,
	[DailyQuest.HelpTheCacklingCannoneerOrTheChucklingScoutFindTreasureInStarlightDesert]: null,
	[DailyQuest.HelpTheBumblingBoatswainOrTheAssemblyGuideFindTreasureInSanctuaryIslands]: null,
	[DailyQuest.HelpTheCeasingCommodoreOrTheDaydreamForesterFindTreasureInHiddenForest]: null,
	[DailyQuest.HelpTheAnxiousAnglerOrTheScoldingStudentFindTreasureInVillageOfDreams]: null,
	[DailyQuest.HelpTheCacklingCannoneerOrTheChucklingScoutFindTreasureInTreasureReef]: null,
	[DailyQuest.HelpTheBumblingBoatswainOrTheAssemblyGuideFindTreasureInStarlightDesert]: null,
	[DailyQuest.HelpTheCeasingCommodoreOrTheDaydreamForesterFindTreasureInSanctuaryIslands]: null,
	[DailyQuest.HelpTheAnxiousAnglerOrTheScoldingStudentFindTreasureInHiddenForest]: null,
	[DailyQuest.HelpTheCacklingCannoneerOrTheChucklingScoutFindTreasureInVillageOfDreams]: null,
	[DailyQuest.MeetUpWithPleadingChildInRepositoryOfRefuge]: null,
	[DailyQuest.MeetUpWithAsceticMonkInPrairiePeaks]: null,
	[DailyQuest.MeetUpWithReassuringRangerInPrairiePeaks]: null,
	[DailyQuest.MeetUpWithBlushingProspectorInValleyOfTriumph]: null,
	[DailyQuest.InvestigateABlueBirdSightingInTheIceRink]: null,
	[DailyQuest.InvestigateABlueBirdSightingInTheVaultRepository]: null,
	[DailyQuest.InvestigateABlueBirdSightingInVillageTheatre]: null,
	[DailyQuest.InvestigateABlueBirdSightingInTheForestClearing]: null,
	[DailyQuest.FindAClueOfTheBlueBirdsWhereaboutsInTheIceRink]: null,
	[DailyQuest.FindAClueOfTheBlueBirdsWhereaboutsInTheVaultRepository]: null,
	[DailyQuest.FindAClueOfTheBlueBirdsWhereaboutsInVillageTheatre]: null,
	[DailyQuest.FindAClueOfTheBlueBirdsWhereaboutsInTheForestClearing]: null,
	[DailyQuest.MeetUpWithBumblingBoatswainInTreasureReef]: null,
	[DailyQuest.MeetUpWithTalentedBuilderInBirdNest]: null,
	[DailyQuest.MeetUpWithTinkeringChimesmithInBirdNest]: null,
	[DailyQuest.MeetUpWithLightWhispererInBirdNest]: null,
	[DailyQuest.MeetUpWithLivelyNavigatorInBirdNest]: null,
	[DailyQuest.PickUpACrab]: null,
	[DailyQuest.AdmireSharedSpacesAtTheBrokenBellTowerInAviaryVillageForAShortWhile]: null,
	[DailyQuest.MeetUpWithGratefulShellCollectorInAviaryVillage]: null,
	[DailyQuest.MeetUpWithSparklerParentInAviaryVillage]: null,
	[DailyQuest.MeetUpWithAsceticMonkInAviaryVillage]: null,
	[DailyQuest.AdmireSharedSpacesWithApplaudingBellmaker]: null,
	[DailyQuest.AdmireSharedSpacesWithDaydreamForester]: null,
	[DailyQuest.AdmireSharedSpacesWithBearhugHermit]: null,
	[DailyQuest.AdmireSharedSpacesWithBumblingBoatswain]: null,
	[DailyQuest.MeetUpWithFlightGuideInPrairieVillage]: null,
	[DailyQuest.MeetUpWithLaughingLightCatcherInValleyOfTriumph]: null,
	[DailyQuest.MeetUpWithCourageousSoldierInValleyOfTriumph]: null,
	[DailyQuest.MeetUpWithFlightGuideInPrairieTemple]: null,
	[DailyQuest.MeetUpWithBackflippingChampionInValleyOfTriumph]: null,
	[DailyQuest.HelpThePrayingAcolyteArchiveSummerIntheArchives]: null,
	[DailyQuest.MeetUpWithThoughtfulDirectorInVaultOfKnowledge]: null,
	[DailyQuest.MeetUpWithApplaudingBellmakerInDaylightPrairie]: null,
	[DailyQuest.MeetUpWithFestivalSpinDancerInForestBrook]: null,
	[DailyQuest.MeetUpWithAdmiringActorInBirdNest]: null,
	[DailyQuest.MeetUpWithTroupeJugglerInGoldenWasteland]: null,
	[DailyQuest.MeetUpWithThoughtfulDirectorInRepositoryOfRefuge]: null,
	[DailyQuest.CatchThe3LightsDuringTheValleysSlidingRace]: null,
	[DailyQuest.InviteASeasonOfMigrationSpiritToAdventureWithYouToday]: null,
	[DailyQuest.MeetUpWithTumblingTroublemakerInPrairieCave]: null,
	[DailyQuest.UseExpressionsWithPlayers]: null,
	[DailyQuest.CatchThe3LightsInTheForestBrook]: null,
	[DailyQuest.CatchThe3LightsInThePrairiesBirdNest]: null,
	[DailyQuest.CatchThe3LightsInPrairieVillage]: null,
	[DailyQuest.CatchThe3LightsInTheWastelandsGraveyard]: null,
	[DailyQuest.CatchThe3LightsUnderTheSeaInTreasureReef]: null,
	[DailyQuest.CatchThe3LightsOnTheVaultsFourthFloor]: null,
	[DailyQuest.CatchThe3LightsInTheVaultsRepositoryOfRefuge]: null,
	[DailyQuest.CatchThe3LightsInTheBigTreehouse]: null,
	[DailyQuest.CatchThe3LightsInTheValleysCitadel]: null,
	[DailyQuest.RideAGiantMantaInSanctuaryIslands]: null,
	[DailyQuest.AdmireSharedSpacesWithTalentedBuilder]: null,
	[DailyQuest.FlyWithManyButterfliesInButterflyFields]: null,
	[DailyQuest.MeetUpWithMelancholyMopeInForestBrook]: null,
	[DailyQuest.FinishNatsBroomstickRaceInCacklingCrab]: null,
	[DailyQuest.HelpAustinCollect5CrabsInTheBasementOfTheCacklingCrab]: null,
	[DailyQuest.HelpSkidmoreFireTheCannons3TimesInTheCacklingCrab]: null,
	[DailyQuest.HopIntoYoshisCauldronBrewInTheCacklingCrab]: null,
	[DailyQuest.MeetUpWithOddballOutcastInHiddenForest]: null,
} as const satisfies Readonly<Record<DailyQuests, string | null>>;
