export const WEBSITE_URL = "https://thatskyapplication.com" as const;
export const WIKI_URL = "https://sky-children-of-the-light.fandom.com" as const;

export const DailyQuest = {
	Collect30PiecesOfLight: 0,
	Light20Candles: 1,
	ForgeACandle: 2,
	Melt10Darkness: 3,
	BowAtAPlayer: 4,
	FollowAFriend: 5,
	HugAFriend: 6,
	WaveToAFriend: 7,
	HoldAFriendsHand: 8,
	SendAGiftToAFriend: 9,
	MakeANewAcquaintance: 10,
	HighFiveAFriend: 11,
	UseAnExpressionNearAFriend: 12,
	SitOnABenchWithAStranger: 13,
	RechargeFromAJellyfish: 14,
	RechargeFromALightBloom: 15,
	RideWithAManta: 16,
	ReliveASpiritsMemories: 17,
	ReliveASpiritsMemoriesInDaylightPrairie: 18,
	ReliveASpiritsMemoriesInHiddenForest: 19,
	ReliveASpiritsMemoriesInValleyOfTriumph: 20,
	ReliveASpiritsMemoriesInGoldenWasteland: 21,
	ReliveASpiritsMemoriesInVaultOfKnowledge: 22,
	FaceTheDarkDragon: 23,
	KnockOver5DarkCrabs: 24,
	CatchTheLightInTheDaylightPrairie: 25,
	CatchTheLightInTheHiddenForest: 26,
	CatchTheLightInTheValleyOfTriumph: 27,
	CatchTheLightInTheGoldenWasteland: 28,
	CatchTheLightInTheVaultOfKnowledge: 29,
	VisitTheCosyHideoutInTheDaylightPrairie: 30,
	VisitTheAncestorsTableOfBelongingInTheHiddenForest: 31,
	VisitTheHotSpringInTheValleyOfTriumph: 32,
	VisitTheBonfireAtTheGoldenWasteland: 33,
	AdmireTheSaplingInTheDaylightPrairie: 34,
	AdmireTheSaplingInTheHiddenForest: 35,
	AdmireTheSaplingInTheValleyOfTriumph: 36,
	AdmireTheSaplingInTheGoldenWasteland: 37,
	AdmireTheSaplingInTheVaultOfKnowledge: 38,
	VisitThePollutedGeyser: 39,
	RidTheSanctuaryVortexOfDarkness: 40,
	FindTheCandlesAtTheEndOfTheRainbowInTheDaylightPrairie: 41,
	FindTheCandlesAtTheEndOfTheRainbowInTheHiddenForest: 42,
	FindTheCandlesAtTheEndOfTheRainbowInTheValleyOfTriumph: 43,
	FindTheCandlesAtTheEndOfTheRainbowInTheGoldenWasteland: 44,
	FindTheCandlesAtTheEndOfTheRainbowInTheVaultOfKnowledge: 45,
	AdmireTheRainbowInTheSanctuaryIslands: 46,
	AdmireTheRainbowInTheWindPaths: 47,
	AdmireTheRainbowInTheHermitValley: 48,
	AdmireTheRainbowInTheTreasureReef: 49,
	AdmireTheRainbowInTheStarlightDesert: 50,
	MeditateAtTheBirdNest: 51,
	MeditateInTheButterflyFields: 52,
	MeditateAtTheSanctuaryIslands: 53,
	MeditateInTheCave: 54,
	MeditateByTheKoiPond: 55,
	MeditateAtTheForestClearing: 56,
	MeditateAtTheForestBrook: 57,
	MeditateAtTheElevatedClearing: 58,
	MeditateAtTheForestEnd: 59,
	MeditateAtTheBoneyard: 60,
	MeditateByTheIceRink: 61,
	MeditateAboveTheCitadelsArch: 62,
	MeditateHighAboveTheCitadel: 63,
	MeditateAtTheColiseum: 64,
	MeditateInTheBrokenTemple: 65,
	MeditateInTheForgottenArk: 66,
	MeditateInTheGraveyard: 67,
	MeditateOnTheBoat: 68,
	MeditateOnTheBattlefield: 69,
	MeditateAtTheVaultEntrance: 70,
	MeditateInTheVaultSecondFloor: 71,
	MeditateAtTheVaultSummit: 72,
	CollectGreenLight: 73,
	CollectOrangeLight: 74,
	CollectBlueLight: 75,
	CollectRedLight: 76,
	CollectPurpleLight: 77,
	PracticeWithTheSkater: 78,
	RaceDownTheSlopesWithTheSkater: 79,
	RaceDownTheMountainWithTheSkater: 80,
	RehearseForAPerformanceWithTheSkater: 81,
	CompleteTheHoopScavengerHunt: 82,
	ReliveTheButterflyCharmer: 83,
	ReliveTheApplaudingBellmaker: 84,
	ReliveTheWavingBellmaker: 85,
	ReliveTheSlumberingShipwright: 86,
	ReliveTheLaughingLightCatcher: 87,
	ReliveTheBirdWhisperer: 88,
	ReliveTheExhaustedDockWorker: 89,
	ReliveTheCeremonialWorshiper: 90,
	ReliveTheShiveringTrailblazer: 91,
	ReliveTheBlushingProspector: 92,
	ReliveTheHideNSeekPioneer: 93,
	ReliveThePoutyPorter: 94,
	ReliveTheDismayedHunter: 95,
	ReliveTheApologeticLumberjack: 96,
	ReliveTheTearfulLightMiner: 97,
	ReliveTheWhaleWhisperer: 98,
	ReliveTheConfidentSightseer: 99,
	ReliveTheHandstandingThrillseeker: 100,
	ReliveTheMantaWhisperer: 101,
	ReliveTheBackflippingChampion: 102,
	ReliveTheCheerfulSpectator: 103,
	ReliveTheBowingMedalist: 104,
	ReliveTheProudVictor: 105,
	ReliveTheFrightenedRefugee: 106,
	ReliveTheFaintingWarrior: 107,
	ReliveTheCourageousSoldier: 108,
	ReliveTheStealthySurvivor: 109,
	ReliveTheSalutingCaptain: 110,
	ReliveTheLookoutScout: 111,
	ReliveThePrayingAcolyte: 112,
	ReliveTheLevitatingAdept: 113,
	ReliveThePoliteScholar: 114,
	ReliveTheMemoryWhisperer: 115,
	ReliveTheMeditatingMonastic: 116,
	ReliveTheStretchingGuru: 117,
	ReliveTheProvokingPerformer: 118,
	ReliveTheLeapingDancer: 119,
	ReliveTheSalutingProtector: 120,
	ReliveTheGreetingShaman: 121,
	ReliveTheDoublefiveLightCatcher: 122,
	ReliveTheLaidbackPioneer: 123,
	ReliveTheTwirlingChampion: 124,
	ReliveTheCrabWhisperer: 125,
	ReliveTheShushingLightScholar: 126,
	ReliveTheConfettiCousin: 127,
	ReliveTheHairtousleTeen: 128,
	ReliveTheSparklerParent: 129,
	ReliveThePleafulParent: 130,
	ReliveTheWiseGrandparent: 131,
	ReliveTheFestivalSpinDancer: 132,
	ReliveTheAdmiringActor: 133,
	ReliveTheTroupeJuggler: 134,
	ReliveTheRespectfulPianist: 135,
	ReliveTheThoughtfulDirector: 136,
	ReliveTheNoddingMuralist: 137,
	ReliveTheIndifferentAlchemist: 138,
	ReliveTheCrabWalker: 139,
	ReliveTheScarecrowFarmer: 140,
	ReliveTheSnoozingCarpenter: 141,
	ReliveThePlayfightingHerbalist: 142,
	ReliveTheJellyWhisperer: 143,
	ReliveTheTimidBookworm: 144,
	ReliveTheRallyingThrillseeker: 145,
	ReliveTheHikingGrouch: 146,
	ReliveTheGratefulShellCollector: 147,
	ReliveTheChillSunbather: 148,
	ReliveTheSpinningMentor: 149,
	ReliveTheDancingPerformer: 150,
	ReliveThePeekingPostman: 151,
	ReliveTheBearhugHermit: 152,
	ReliveTheBaffledBotanist: 153,
	ReliveTheScoldingStudent: 154,
	ReliveTheScaredyCadet: 155,
	ReliveTheMarchingAdventurer: 156,
	ReliveTheChucklingScout: 157,
	ReliveTheDaydreamForester: 158,
	VisitAShardOfDarknessFallenToTheKingdomOfSky: 159,
	TakeASelfieWithHikingGrouchInPrairiePeaks: 160,
	TakeASelfieWithCrabWhispererInPrairiePeaks: 161,
	TakeASelfieWithCacklingCannoneerInPrairiePeaks: 162,
	TakeASelfieWithTroupeGreeterInPrairiePeaks: 163,
	MeetCinnamorollOnAHillInAviaryVillage: 164,
	SmellFlowersWithCinnamorollInAviaryVillage: 165,
	FindCinnamorollPeekingAroundAviaryVillage: 166,
	WakeUpCinnamorollInAviaryVillage: 167,
	FlyUpToTheTowerWithCinnamorollInAviaryVillage: 168,
	SplashInTheWaterWithCinnamorollInAviaryVillage: 169,
	PlayAnyTournamentSport: 170,
	ModestDancerNeedsHelpWithSomethingInVillageOfDreams: 171,
	ForgetfulStorytellerNeedsHelpWithSomethingInVillageOfDreams: 172,
	MeetUpWithFranticStagehandInVillageTheatre: 173,
	MellowMusicianNeedsHelpWithSomethingInVillageTheatre: 174,
	ChangeYourHairstyle: 175,
	ChangeYourNecklace: 176,
	ChangeYourProp: 177,
	ChangeYourMask: 178,
	ChangeYourCape: 179,
	ChangeYourOutfit: 180,
	ViewASharedMemoryAtAStyleRunwayShrine: 181,
	RecordASharedMemoryAtAStyleRunwayShrine: 182,
	CacklingCannoneerNeedsHelpWithSomethingInTreasureReef: 183,
	AnxiousAnglerNeedsHelpWithSomethingInTreasureReef: 184,
	MellowMusicianNeedsHelpWithSomethingInVillageOfDreams: 185,
	AnxiousAnglerNeedsHelpWithSomethingInGoldenWasteland: 186,
	MeetUpWithAnxiousAnglerInCrabFields: 187,
	MeetUpWithCeasingCommodoreInTreasureReef: 188,
	MeetUpWithBlushingProspectorInForestBrook: 189,
	MeetUpWithShiveringTrailblazerInForestBrook: 190,
	MeetUpWithCacklingCannoneerInGraveyard: 191,
	MeetUpWithHideNSeekPioneerInBoneyard: 192,
	MeetUpWithHideNSeekPioneerInElevatedClearing: 193,
	MeetUpWithBumblingBoatswainInForgottenArk: 194,
	MeetUpWithHideNSeekPioneerInHiddenForest: 195,
	MeetUpWithCacklingCannoneerInForgottenArk: 196,
	MeetUpWithApologeticLumberjackInBoneyard: 197,
	MeetUpWithCeasingCommodoreInForgottenArk: 198,
	MeetUpWithJollyGeologistInPrairiePeaks: 199,
	MeetUpWithDismayedHunterInBoneyard: 200,
	MeetUpWithWhaleWhispererInBoneyard: 201,
	MeetUpWithAsceticMonkInSanctuaryIslands: 202,
	MeetUpWithNightbirdWhispererInSanctuaryIslands: 203,
	MeetUpWithJollyGeologistInSanctuaryIslands: 204,
	MeetUpWithAsceticMonkInPrairieVillage: 205,
} as const satisfies Readonly<Record<string, number>>;

export const DAILY_QUEST_VALUES = Object.values(DailyQuest);
export type DailyQuests = (typeof DAILY_QUEST_VALUES)[number];

export enum RealmName {
	IslesOfDawn = "Isles of Dawn",
	DaylightPrairie = "Daylight Prairie",
	HiddenForest = "Hidden Forest",
	ValleyOfTriumph = "Valley of Triumph",
	GoldenWasteland = "Golden Wasteland",
	VaultOfKnowledge = "Vault of Knowledge",
	EyeOfEden = "Eye of Eden",
}

export enum SkyMap {
	// Daylight Prairie.
	BirdNest = "Bird Nest",
	ButterflyFields = "Butterfly Fields",
	Cave = "Cave",
	KoiPond = "Koi Pond",
	VillageIslands = "Village Islands",
	SanctuaryIslands = "Sanctuary Islands",

	// Hidden Forest.
	Boneyard = "Boneyard",
	ElevatedClearing = "Elevated Clearing",
	ForestBrook = "Forest Brook",
	ForestClearing = "Forest Clearing",
	ForestEnd = "Forest End",
	Treehouse = "Treehouse",
	WindPaths = "Wind Paths",

	// Valley of Triumph.
	IceRink = "Ice Rink",
	Citadel = "Citadel",
	Coliseum = "Coliseum",
	HermitValley = "Hermit Valley",
	VillageOfDreams = "Village of Dreams",

	// Golden Wasteland.
	Battlefield = "Battlefield",
	Boat = "Boat",
	BrokenTemple = "Broken Temple",
	CrabFields = "Crab Fields",
	ForgottenArk = "Forgotten Ark",
	Graveyard = "Graveyard",
	TreasureReef = "Treasure Reef",

	// Vault of Knowledge.
	VaultEntrance = "Vault Entrance",
	JellyfishCove = "Jellyfish Cove",
	StarlightDesert = "Starlight Desert",
	VaultSecondFloor = "Vault Second Floor",
	VaultSummit = "Vault Summit",

	// Orbit.
	Orbit = "Orbit",

	// Season of Shattering.
	AncientMemory = "Ancient Memory",

	// Season of the Nine-Coloured Deer.
	CrescentOasis = "Crescent Oasis",
}

export const MAXIMUM_HAIR_TOUSLE_GIF = 3 as const;
export const MAXIMUM_HIGH_FIVE_GIF = 8 as const;
export const MAXIMUM_HUG_GIF = 36 as const;
export const MAXIMUM_PLAY_FIGHT_GIF = 6 as const;
export const MAXIMUM_KRILL_GIF = 11 as const;

// biome-ignore lint/performance/noBarrelFile: This is fine.
export { Cosmetic } from "./cosmetics.js";
export { type Emoji, emojis, formatEmoji, formatEmojiURL, resolveCurrencyEmoji } from "./emojis.js";
export { PlatformId, PLATFORM_ID_VALUES, type PlatformIds, isPlatformId } from "./platforms.js";
export { SeasonId, type SeasonIds, isSeasonId } from "./season.js";
export {
	FriendAction,
	SPIRIT_TYPE,
	SpiritCall,
	SpiritEmote,
	SpiritName,
	SpiritStance,
	type SpiritType,
} from "./spirits.js";
