import { SpiritId } from "./utility/spirits.js";

export const NotificationType = {
	DailyReset: 0,
	EyeOfEden: 1,
	InternationalSpaceStation: 2,
	Dragon: 3,
	PollutedGeyser: 4,
	Grandma: 5,
	Turtle: 6,
	RegularShardEruption: 7,
	StrongShardEruption: 8,
	AURORA: 9,
	Passage: 10,
	AviarysFireworkFestival: 11,
	TravellingSpirit: 12,
	DreamsSkater: 13,
	NestingWorkshop: 14,
	Maintenance: 15,
	Events: 16,
	RadianceEvent: 17,
	Seasons: 18,
	DoubleHearts: 19,
	DoubleSeasonalLight: 20,
	DoubleTreasureCandles: 21,
	ReturningSpirits: 22,
} as const satisfies Readonly<Record<string, number>>;

export type NotificationTypes = (typeof NotificationType)[keyof typeof NotificationType];
export const NOTIFICATION_TYPE_VALUES = Object.values(NotificationType);

export const NotificationTypeToLocaleKey = {
	[NotificationType.DailyReset]: `general:notification-types.${NotificationType.DailyReset}`,
	[NotificationType.EyeOfEden]: "general:areas.Eye of Eden",
	[NotificationType.InternationalSpaceStation]: `general:notification-types.${NotificationType.InternationalSpaceStation}`,
	[NotificationType.Dragon]: `general:notification-types.${NotificationType.Dragon}`,
	[NotificationType.PollutedGeyser]: `general:notification-types.${NotificationType.PollutedGeyser}`,
	[NotificationType.Grandma]: `general:notification-types.${NotificationType.Grandma}`,
	[NotificationType.Turtle]: `general:notification-types.${NotificationType.Turtle}`,
	[NotificationType.RegularShardEruption]: `general:notification-types.${NotificationType.RegularShardEruption}`,
	[NotificationType.StrongShardEruption]: `general:notification-types.${NotificationType.StrongShardEruption}`,
	[NotificationType.AURORA]: `general:spirits.${SpiritId.AURORA}`,
	[NotificationType.Passage]: `general:notification-types.${NotificationType.Passage}`,
	[NotificationType.AviarysFireworkFestival]: "general:event-names.aviarys-firework-festival",
	[NotificationType.TravellingSpirit]: "general:travelling-spirit",
	[NotificationType.DreamsSkater]: `general:notification-types.${NotificationType.DreamsSkater}`,
	[NotificationType.NestingWorkshop]: `general:notification-types.${NotificationType.NestingWorkshop}`,
	[NotificationType.Maintenance]: "general:maintenance",
	[NotificationType.Events]: "general:events",
	[NotificationType.RadianceEvent]: "general:event-names.radiance-event",
	[NotificationType.Seasons]: "general:season-plural",
	[NotificationType.DoubleHearts]: "general:event-names.double-hearts",
	[NotificationType.DoubleSeasonalLight]: "general:event-names.double-seasonal-light",
	[NotificationType.DoubleTreasureCandles]: "general:event-names.double-treasure-candles",
	[NotificationType.ReturningSpirits]: "general:returning-spirits",
} as const satisfies Readonly<Record<NotificationTypes, string>>;

// Cannot exceed 24.
export const NotificationOffsetToMaximumValues = {
	[NotificationType.DailyReset]: 15,
	[NotificationType.EyeOfEden]: 24,
	[NotificationType.InternationalSpaceStation]: 10,
	[NotificationType.Dragon]: 10,
	[NotificationType.PollutedGeyser]: 10,
	[NotificationType.Grandma]: 10,
	[NotificationType.Turtle]: 10,
	[NotificationType.RegularShardEruption]: 10,
	[NotificationType.StrongShardEruption]: 10,
	[NotificationType.AURORA]: 15,
	[NotificationType.Passage]: 5,
	[NotificationType.AviarysFireworkFestival]: 15,
	[NotificationType.TravellingSpirit]: 15,
	[NotificationType.DreamsSkater]: 10,
	[NotificationType.NestingWorkshop]: 15,
	[NotificationType.Maintenance]: 15,
	[NotificationType.Events]: 15,
	[NotificationType.RadianceEvent]: 15,
	[NotificationType.Seasons]: 15,
	[NotificationType.DoubleHearts]: 15,
	[NotificationType.DoubleSeasonalLight]: 15,
	[NotificationType.DoubleTreasureCandles]: 15,
	[NotificationType.ReturningSpirits]: 15,
} as const satisfies Readonly<Record<NotificationTypes, number>>;
