import { type EmotesEmojis, EMOTE_EMOJIS } from "./emojis.js";

export enum SpiritName {
	// Isles of Dawn.
	PointingCandlemaker = "Pointing Candlemaker",
	UsheringStargazer = "Ushering Stargazer",
	RejectingVoyager = "Rejecting Voyager",
	ElderOfTheIsle = "Elder of the Isle",

	// Daylight Prairie.
	ButterflyCharmer = "Butterfly Charmer",
	ApplaudingBellmaker = "Applauding Bellmaker",
	WavingBellmaker = "Waving Bellmaker",
	SlumberingShipwright = "Slumbering Shipwright",
	LaughingLightCatcher = "Laughing Light Catcher",
	BirdWhisperer = "Bird Whisperer",
	ExhaustedDockWorker = "Exhausted Dock Worker",
	CeremonialWorshiper = "Ceremonial Worshiper",
	ElderOfThePrairie = "Elder of the Prairie",

	// Hidden Forest.
	ShiveringTrailblazer = "Shivering Trailblazer",
	BlushingProspector = "Blushing Prospector",
	HideNSeekPioneer = "Hide'n'Seek Pioneer",
	PoutyPorter = "Pouty Porter",
	DismayedHunter = "Dismayed Hunter",
	ApologeticLumberjack = "Apologetic Lumberjack",
	TearfulLightMiner = "Tearful Light Miner",
	WhaleWhisperer = "Whale Whisperer",
	ElderOfTheForest = "Elder of the Forest",

	// Valley of Triumph.
	ConfidentSightseer = "Confident Sightseer",
	HandstandingThrillseeker = "Handstanding Thrillseeker",
	MantaWhisperer = "Manta Whisperer",
	BackflippingChampion = "Backflipping Champion",
	CheerfulSpectator = "Cheerful Spectator",
	BowingMedalist = "Bowing Medalist",
	ProudVictor = "Proud Victor",
	ElderOfTheValley = "Elder of the Valley",

	// Golden Wasteland.
	FrightenedRefugee = "Frightened Refugee",
	FaintingWarrior = "Fainting Warrior",
	CourageousSoldier = "Courageous Soldier",
	StealthySurvivor = "Stealthy Survivor",
	SalutingCaptain = "Saluting Captain",
	LookoutScout = "Lookout Scout",
	ElderOfTheWasteland = "Elder of the Wasteland",

	// Vault of Knowledge.
	PrayingAcolyte = "Praying Acolyte",
	LevitatingAdept = "Levitating Adept",
	PoliteScholar = "Polite Scholar",
	MemoryWhisperer = "Memory Whisperer",
	MeditatingMonastic = "Meditating Monastic",
	ElderOfTheVault = "Elder of the Vault",

	// Season of Gratitude.
	GratitudeGuide = "Gratitude Guide",
	SassyDrifter = "Sassy Drifter",
	StretchingGuru = "Stretching Guru",
	ProvokingPerformer = "Provoking Performer",
	LeapingDancer = "Leaping Dancer",
	SalutingProtector = "Saluting Protector",
	GreetingShaman = "Greeting Shaman",

	// Season of Lightseekers.
	LightseekerGuide = "Lightseeker Guide",
	PiggybackLightseeker = "Piggyback Lightseeker",
	DoublefiveLightCatcher = "Doublefive Light Catcher",
	LaidbackPioneer = "Laidback Pioneer",
	TwirlingChampion = "Twirling Champion",
	CrabWhisperer = "Crab Whisperer",
	ShushingLightScholar = "Shushing Light Scholar",

	// Season of Belonging.
	BelongingGuide = "Belonging Guide",
	BoogieKid = "Boogie Kid",
	ConfettiCousin = "Confetti Cousin",
	HairtousleTeen = "Hairtousle Teen",
	SparklerParent = "Sparkler Parent",
	PleafulParent = "Pleaful Parent",
	WiseGrandparent = "Wise Grandparent",

	// Season of Rhythm.
	RhythmGuide = "Rhythm Guide",
	TroupeGreeter = "Troupe Greeter",
	FestivalSpinDancer = "Festival Spin Dancer",
	AdmiringActor = "Admiring Actor",
	TroupeJuggler = "Troupe Juggler",
	RespectfulPianist = "Respectful Pianist",
	ThoughtfulDirector = "Thoughtful Director",

	// Season of Enchantment.
	EnchantmentGuide = "Enchantment Guide",
	NoddingMuralist = "Nodding Muralist",
	IndifferentAlchemist = "Indifferent Alchemist",
	CrabWalker = "Crab Walker",
	ScarecrowFarmer = "Scarecrow Farmer",
	SnoozingCarpenter = "Snoozing Carpenter",
	PlayfightingHerbalist = "Playfighting Herbalist",

	// Season of Sanctuary.
	SanctuaryGuide = "Sanctuary Guide",
	JellyWhisperer = "Jelly Whisperer",
	TimidBookworm = "Timid Bookworm",
	RallyingThrillseeker = "Rallying Thrillseeker",
	HikingGrouch = "Hiking Grouch",
	GratefulShellCollector = "Grateful Shell Collector",
	ChillSunbather = "Chill Sunbather",

	// Season of Prophecy.
	ProphecyGuide = "Prophecy Guide",
	ProphetOfWater = "Prophet of Water",
	ProphetOfEarth = "Prophet of Earth",
	ProphetOfAir = "Prophet of Air",
	ProphetOfFire = "Prophet of Fire",

	// Season of Dreams.
	DreamsGuide = "Dreams Guide",
	SpinningMentor = "Spinning Mentor",
	DancingPerformer = "Dancing Performer",
	PeekingPostman = "Peeking Postman",
	BearhugHermit = "Bearhug Hermit",

	// Season of Assembly.
	AssemblyGuide = "Assembly Guide",
	BaffledBotanist = "Baffled Botanist",
	ScoldingStudent = "Scolding Student",
	ScaredyCadet = "Scaredy Cadet",
	MarchingAdventurer = "Marching Adventurer",
	ChucklingScout = "Chuckling Scout",
	DaydreamForester = "Daydream Forester",

	// Season of Little Prince.
	TheRose = "The Rose",
	BeckoningRuler = "Beckoning Ruler",
	GloatingNarcissist = "Gloating Narcissist",
	StretchingLamplighter = "Stretching Lamplighter",
	SlouchingSoldier = "Slouching Soldier",
	SneezingGeographer = "Sneezing Geographer",
	StarCollector = "Star Collector",

	// Season of Flight.
	FlightGuide = "Flight Guide",
	LivelyNavigator = "Lively Navigator",
	LightWhisperer = "Light Whisperer",
	TinkeringChimesmith = "Tinkering Chimesmith",
	TalentedBuilder = "Talented Builder",

	// Season of Abyss.
	AbyssGuide = "Abyss Guide",
	AnxiousAngler = "Anxious Angler",
	CeasingCommodore = "Ceasing Commodore",
	BumblingBoatswain = "Bumbling Boatswain",
	CacklingCannoneer = "Cackling Cannoneer",

	// Season of Performance.
	PerformanceGuide = "Performance Guide",
	FranticStagehand = "Frantic Stagehand",
	ForgetfulStoryteller = "Forgetful Storyteller",
	MellowMusician = "Mellow Musician",
	ModestDancer = "Modest Dancer",

	// Season of Shattering.
	TheVoidOfShattering = "The Void of Shattering",
	AncientLight1 = "Ancient Light (Jellyfish)",
	AncientLight2 = "Ancient Light (Manta)",
	AncientDarkness1 = "Ancient Darkness (Plant)",
	AncientDarkness2 = "Ancient Darkness (Dragon)",

	// Season of AURORA.
	AURORA = "AURORA",
	RunningWayfarer = "Running Wayfarer",
	MindfulMiner = "Mindful Miner",
	WarriorOfLove = "Warrior of Love",
	SeedOfHope = "Seed of Hope",

	// Season of Remembrance.
	RemembranceGuide = "Remembrance Guide",
	BereftVeteran = "Bereft Veteran",
	PleadingChild = "Pleading Child",
	TiptoeingTeaBrewer = "Tiptoeing Tea-Brewer",
	WoundedWarrior = "Wounded Warrior",

	// Season of Passage.
	PassageGuide = "Passage Guide",
	OddballOutcast = "Oddball Outcast",
	TumblingTroublemaker = "Tumbling Troublemaker",
	MelancholyMope = "Melancholy Mope",
	OveractiveOverachiever = "Overactive Overachiever",

	// Season of Moments.
	MomentsGuide = "Moments Guide",
	ReassuringRanger = "Reassuring Ranger",
	NightbirdWhisperer = "Nightbird Whisperer",
	JollyGeologist = "Jolly Geologist",
	AsceticMonk = "Ascetic Monk",

	// Season of Revival.
	HopefulSteward = "Hopeful Steward",
	VestigeOfADesertedOasis = "Vestige of a Deserted Oasis",
	MemoryOfALostVillage = "Memory of a Lost Village",
	EchoOfAnAbandonedRefuge = "Echo of an Abandoned Refuge",
	RemnantOfAForgottenHaven = "Remnant of a Forgotten Haven",

	// Season of the Nine-Colored Deer.
	SpiritOfMural = "Spirit of Mural",
	HerbGatherer = "Herb Gatherer",
	Hunter = "Hunter",
	FeudalLord = "Feudal Lord",
	Princess = "Princess",

	// Season of Nesting.
	NestingGuide = "Nesting Guide",
	NestingSolarium = "Nesting Solarium",
	NestingLoft = "Nesting Loft",
	NestingAtrium = "Nesting Atrium",
	NestingNook = "Nesting Nook",
}

export const enum SpiritEmote {
	Sit = "Sit",
	Point = "Point",
	Come = "Come",
	NoThanks = "No thanks",
	Welcome = "Welcome",
	Nod = "Nod",
	Scold = "Scold",
	Butterfly = "Butterfly",
	Clap = "Clap",
	Wave = "Wave",
	Laugh = "Laugh",
	Yawn = "Yawn",
	WipeBrow = "Wipe brow",
	Teamwork = "Teamwork",
	BlowKiss = "Blow kiss",
	Grateful = "Grateful",
	BellyScratch = "Belly scratch",
	Chuckle = "Chuckle",
	Shiver = "Shiver",
	HideAndSeek = "Hide and seek",
	Angry = "Angry",
	Shy = "Shy",
	Shocked = "Shocked",
	Apologise = "Apologise",
	Crying = "Crying",
	Kabuki = "Kabuki",
	Shrug = "Shrug",
	Grumpy = "Grumpy",
	Peek = "Peek",
	Eww = "Eww",
	Facepalm = "Facepalm",
	Handstand = "Handstand",
	Backflip = "Backflip",
	Bow = "Bow",
	Cheer = "Cheer",
	Leap = "Leap",
	TripleAxel = "Triple axel",
	Confetti = "Confetti",
	BoogieDance = "Boogie dance",
	SpinDance = "Spin dance",
	Juggle = "Juggle",
	CrabWalk = "Crab walk",
	RallyCheer = "Rally cheer",
	SpinTrick = "Spin trick",
	ShowDance = "Show dance",
	Duck = "Duck",
	Faint = "Faint",
	Respect = "Respect",
	LookAround = "Look around",
	Salute = "Salute",
	Acknowledge = "Acknowledge",
	KungFu = "Kung Fu",
	DontGo = "Don't go!",
	Boo = "Boo",
	DustOff = "Dust off",
	ChestPound = "Chest pound",
	Marching = "Marching",
	Telekinesis = "Telekinesis",
	Float = "Float",
	Pray = "Pray",
	Yoga = "Yoga",
	Shush = "Shush",
	Sparkler = "Sparkler",
	Thinking = "Thinking",
	Doze = "Doze",
	Balance = "Balance",
	DeepBreath = "Deep breath",
	Bubbles = "Bubbles",
	Beckon = "Beckon",
	Gloat = "Gloat",
	Stretch = "Stretch",
	Slouch = "Slouch",
	Sneeze = "Sneeze",
	HandRub = "Hand rub",
	Voilà = "Voilà",
	Navigate = "Navigate",
	CalmDown = "Calm down",
	EvilLaugh = "Evil laugh",
	Ouch = "Ouch",
	Anxious = "Anxious",
	Headbob = "Headbob",
	Aww = "Aww",
	WavingLight = "Waving light",
	RaiseTheRoof = "Raise the roof",
	Twirl = "Twirl",
	RhythmicClap = "Rhythmic clap",
	Conduct = "Conduct",
	SilentClap = "Silent clap",
	Skipping = "Skipping",
	Pleading = "Pleading",
	Tiptoeing = "Tiptoeing",
	Grieving = "Grieving",
	HackySack = "Hacky sack",
	Somersault = "Somersault",
	Moping = "Moping",
	PullUp = "Pull-up",
	JollyDance = "Jolly dance",
	BlindfoldBalancePose = "Blindfold balance pose",
	CureForMeDance = "Cure for me dance",
	Whistle = "Whistle",
	Flex = "Flex",
	FloatSpin = "Float spin",
}

export const SpiritEmoteToEmoji = {
	[SpiritEmote.Sit]: EMOTE_EMOJIS.Sit,
	[SpiritEmote.Point]: EMOTE_EMOJIS.Point,
	[SpiritEmote.Come]: EMOTE_EMOJIS.Come,
	[SpiritEmote.NoThanks]: EMOTE_EMOJIS.NoThanks,
	[SpiritEmote.Welcome]: EMOTE_EMOJIS.Welcome,
	[SpiritEmote.Nod]: EMOTE_EMOJIS.Nod,
	[SpiritEmote.Scold]: EMOTE_EMOJIS.Scold,
	[SpiritEmote.Butterfly]: EMOTE_EMOJIS.Butterfly,
	[SpiritEmote.Clap]: EMOTE_EMOJIS.Clap,
	[SpiritEmote.Wave]: EMOTE_EMOJIS.Wave,
	[SpiritEmote.Laugh]: EMOTE_EMOJIS.Laugh,
	[SpiritEmote.Yawn]: EMOTE_EMOJIS.Yawn,
	[SpiritEmote.WipeBrow]: EMOTE_EMOJIS.WipeBrow,
	[SpiritEmote.Teamwork]: EMOTE_EMOJIS.Teamwork,
	[SpiritEmote.BlowKiss]: EMOTE_EMOJIS.BlowKiss,
	[SpiritEmote.Grateful]: EMOTE_EMOJIS.Grateful,
	[SpiritEmote.BellyScratch]: EMOTE_EMOJIS.BellyScratch,
	[SpiritEmote.Chuckle]: EMOTE_EMOJIS.Chuckle,
	[SpiritEmote.Shiver]: EMOTE_EMOJIS.Shiver,
	[SpiritEmote.HideAndSeek]: EMOTE_EMOJIS.HideAndSeek,
	[SpiritEmote.Angry]: EMOTE_EMOJIS.Angry,
	[SpiritEmote.Shy]: EMOTE_EMOJIS.Shy,
	[SpiritEmote.Shocked]: EMOTE_EMOJIS.Shocked,
	[SpiritEmote.Apologise]: EMOTE_EMOJIS.Apologise,
	[SpiritEmote.Crying]: EMOTE_EMOJIS.Crying,
	[SpiritEmote.Kabuki]: EMOTE_EMOJIS.Kabuki,
	[SpiritEmote.Shrug]: EMOTE_EMOJIS.Shrug,
	[SpiritEmote.Grumpy]: EMOTE_EMOJIS.Grumpy,
	[SpiritEmote.Peek]: EMOTE_EMOJIS.Peek,
	[SpiritEmote.Eww]: EMOTE_EMOJIS.Eww,
	[SpiritEmote.Facepalm]: EMOTE_EMOJIS.Facepalm,
	[SpiritEmote.Handstand]: EMOTE_EMOJIS.Handstand,
	[SpiritEmote.Backflip]: EMOTE_EMOJIS.Backflip,
	[SpiritEmote.Bow]: EMOTE_EMOJIS.Bow,
	[SpiritEmote.Cheer]: EMOTE_EMOJIS.Cheer,
	[SpiritEmote.Leap]: EMOTE_EMOJIS.Leap,
	[SpiritEmote.TripleAxel]: EMOTE_EMOJIS.TripleAxel,
	[SpiritEmote.Confetti]: EMOTE_EMOJIS.Confetti,
	[SpiritEmote.BoogieDance]: EMOTE_EMOJIS.BoogieDance,
	[SpiritEmote.SpinDance]: EMOTE_EMOJIS.SpinDance,
	[SpiritEmote.Juggle]: EMOTE_EMOJIS.Juggle,
	[SpiritEmote.CrabWalk]: EMOTE_EMOJIS.CrabWalk,
	[SpiritEmote.RallyCheer]: EMOTE_EMOJIS.RallyCheer,
	[SpiritEmote.SpinTrick]: EMOTE_EMOJIS.SpinTrick,
	[SpiritEmote.ShowDance]: EMOTE_EMOJIS.ShowDance,
	[SpiritEmote.Duck]: EMOTE_EMOJIS.Duck,
	[SpiritEmote.Faint]: EMOTE_EMOJIS.Faint,
	[SpiritEmote.Respect]: EMOTE_EMOJIS.Respect,
	[SpiritEmote.LookAround]: EMOTE_EMOJIS.LookAround,
	[SpiritEmote.Salute]: EMOTE_EMOJIS.Salute,
	[SpiritEmote.Acknowledge]: EMOTE_EMOJIS.Acknowledge,
	[SpiritEmote.KungFu]: EMOTE_EMOJIS.KungFu,
	[SpiritEmote.DontGo]: EMOTE_EMOJIS.DontGo,
	[SpiritEmote.Boo]: EMOTE_EMOJIS.Boo,
	[SpiritEmote.DustOff]: EMOTE_EMOJIS.DustOff,
	[SpiritEmote.ChestPound]: EMOTE_EMOJIS.ChestPound,
	[SpiritEmote.Marching]: EMOTE_EMOJIS.Marching,
	[SpiritEmote.Telekinesis]: EMOTE_EMOJIS.Telekinesis,
	[SpiritEmote.Float]: EMOTE_EMOJIS.Float,
	[SpiritEmote.Pray]: EMOTE_EMOJIS.Pray,
	[SpiritEmote.Yoga]: EMOTE_EMOJIS.Yoga,
	[SpiritEmote.Shush]: EMOTE_EMOJIS.Shush,
	[SpiritEmote.Sparkler]: EMOTE_EMOJIS.Sparkler,
	[SpiritEmote.Thinking]: EMOTE_EMOJIS.Thinking,
	[SpiritEmote.Doze]: EMOTE_EMOJIS.Doze,
	[SpiritEmote.Balance]: EMOTE_EMOJIS.Balance,
	[SpiritEmote.DeepBreath]: EMOTE_EMOJIS.DeepBreath,
	[SpiritEmote.Bubbles]: EMOTE_EMOJIS.Bubbles,
	[SpiritEmote.Beckon]: EMOTE_EMOJIS.Beckon,
	[SpiritEmote.Gloat]: EMOTE_EMOJIS.Gloat,
	[SpiritEmote.Stretch]: EMOTE_EMOJIS.Stretch,
	[SpiritEmote.Slouch]: EMOTE_EMOJIS.Slouch,
	[SpiritEmote.Sneeze]: EMOTE_EMOJIS.Sneeze,
	[SpiritEmote.HandRub]: EMOTE_EMOJIS.HandRub,
	[SpiritEmote.Voilà]: EMOTE_EMOJIS.Voilà,
	[SpiritEmote.Navigate]: EMOTE_EMOJIS.Navigate,
	[SpiritEmote.CalmDown]: EMOTE_EMOJIS.CalmDown,
	[SpiritEmote.EvilLaugh]: EMOTE_EMOJIS.EvilLaugh,
	[SpiritEmote.Ouch]: EMOTE_EMOJIS.Ouch,
	[SpiritEmote.Anxious]: EMOTE_EMOJIS.Anxious,
	[SpiritEmote.Headbob]: EMOTE_EMOJIS.Headbob,
	[SpiritEmote.Aww]: EMOTE_EMOJIS.Aww,
	[SpiritEmote.WavingLight]: EMOTE_EMOJIS.WavingLight,
	[SpiritEmote.RaiseTheRoof]: EMOTE_EMOJIS.RaiseTheRoof,
	[SpiritEmote.Twirl]: EMOTE_EMOJIS.Twirl,
	[SpiritEmote.RhythmicClap]: EMOTE_EMOJIS.RhythmicClap,
	[SpiritEmote.Conduct]: EMOTE_EMOJIS.Conduct,
	[SpiritEmote.SilentClap]: EMOTE_EMOJIS.SilentClap,
	[SpiritEmote.Skipping]: EMOTE_EMOJIS.Skipping,
	[SpiritEmote.Pleading]: EMOTE_EMOJIS.Pleading,
	[SpiritEmote.Tiptoeing]: EMOTE_EMOJIS.Tiptoeing,
	[SpiritEmote.Grieving]: EMOTE_EMOJIS.Grieving,
	[SpiritEmote.HackySack]: EMOTE_EMOJIS.HackySack,
	[SpiritEmote.Somersault]: EMOTE_EMOJIS.Somersault,
	[SpiritEmote.Moping]: EMOTE_EMOJIS.Moping,
	[SpiritEmote.PullUp]: EMOTE_EMOJIS.PullUp,
	[SpiritEmote.JollyDance]: EMOTE_EMOJIS.JollyDance,
	[SpiritEmote.BlindfoldBalancePose]: EMOTE_EMOJIS.BlindfoldBalancePose,
	[SpiritEmote.CureForMeDance]: EMOTE_EMOJIS.CureForMeDance,
	[SpiritEmote.Whistle]: EMOTE_EMOJIS.Whistle,
	[SpiritEmote.Flex]: EMOTE_EMOJIS.Flex,
	[SpiritEmote.FloatSpin]: EMOTE_EMOJIS.FloatSpin,
} as const satisfies Readonly<Record<SpiritEmote, EmotesEmojis>>;

export const enum SpiritStance {
	Base = "Base",
	Courageous = "Courageous",
	Confident = "Confident",
	Sneaky = "Sneaky",
	Proud = "Proud",
	Polite = "Polite",
	Sassy = "Sassy",
	Laidback = "Laidback",
	Wise = "Wise",
	Timid = "Timid",
	Tinker = "Tinker",
	Injured = "Injured",
}

export const enum SpiritCall {
	Base = "Base",
	Bird = "Bird",
	Whale = "Whale",
	Manta = "Manta",
	CosmicManta = "Cosmic manta",
	Crab = "Crab",
	Jellyfish = "Jellyfish",
	BabyManta = "Baby manta",
	Nightbird = "Nightbird",

	// From the Kizuna-AI pin.
	KizunaAI = "Kizuna-AI",

	// From the PlayStation starter pack.
	Journey = "Journey",
}

export const enum FriendAction {
	HoldHand = "Hold hand",
	HighFive = "High-five",
	Hug = "Hug",
	FistBump = "Fist bump",
	DoubleFive = "Double-five",
	HairTousle = "Hair tousle",
	Carry = "Carry",
	PlayFight = "Play fight",
	Bearhug = "Bearhug",
	Handshake = "Handshake",
	DuetDance = "Duet dance",
	SideHug = "Side hug",
	CradleCarry = "Cradle carry",
}

export const SPIRIT_TYPE = {
	Standard: 0,
	Elder: 1,
	Seasonal: 2,
	Guide: 3,
} as const satisfies Readonly<Record<string, number>>;

export type SpiritType = (typeof SPIRIT_TYPE)[keyof typeof SPIRIT_TYPE];

export const SpiritTypeToString = {
	[SPIRIT_TYPE.Standard]: "Standard Spirits",
	[SPIRIT_TYPE.Elder]: "Elders",
	[SPIRIT_TYPE.Seasonal]: "Seasonal Spirits",
	[SPIRIT_TYPE.Guide]: "Guide Spirits",
} as const satisfies Readonly<Record<SpiritType, string>>;
