/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface BlueskyWebhooks {
  did: string;
  guild_id: string;
  webhook_id: string;
  webhook_token: string;
}

export interface Catalogue {
  data: Generated<number[]>;
  last_updated_at: Timestamp | null;
  show_everything_button: Generated<boolean>;
  user_id: string;
}

export interface Checklist {
  daily_quests: Generated<boolean>;
  event_tickets: Generated<boolean>;
  eye_of_eden: Generated<boolean>;
  last_updated_at: Timestamp;
  seasonal_candles: Generated<boolean>;
  shard_eruptions: Generated<boolean>;
  user_id: string;
}

export interface DailyGuides {
  last_updated_at: Generated<Timestamp>;
  last_updated_user_id: string;
  quest1: number | null;
  quest2: number | null;
  quest3: number | null;
  quest4: number | null;
  travelling_rock: string | null;
}

export interface DailyGuidesDistribution {
  channel_id: string | null;
  guild_id: string;
  message_id: string | null;
  type: number;
}

export interface Feedback {
  completed_at: Timestamp;
  question1: string;
  question2: string;
  question3: string;
  question4: string;
  user_id: string;
}

export interface FeedbackUpsell {
  created_at: Timestamp;
  user_id: string;
}

export interface FriendshipActions {
  id: number;
  reference: string | null;
  skip: boolean;
  square: boolean;
  type: number;
  users: string[];
}

export interface Giveaway {
  eligible: boolean;
  entry_count: number;
  last_entry_at: Timestamp;
  user_id: string;
}

export interface GiveawayUpsell {
  user_id: string;
}

export interface Guess {
  date: Timestamp | null;
  streak: number | null;
  type: number;
  user_id: string;
}

export interface Hearts {
  count: number;
  giftee_id: string | null;
  timestamp: Timestamp;
  user_id: string | null;
}

export interface Messages {
  channel_id: string;
  content: string;
  created_at: Timestamp;
  guild_id: string;
  message_id: string;
  reply_message_id: string | null;
  user_id: string;
}

export interface Notifications {
  channel_id: string | null;
  guild_id: string;
  locale: string;
  offset: number | null;
  role_id: string | null;
  sendable: boolean;
  type: number;
}

export interface SkyProfileLikes {
  target_id: string;
  user_id: string;
}

export interface SkyProfiles {
  banner: Generated<string | null>;
  catalogue_progression: boolean | null;
  country: string | null;
  description: Generated<string | null>;
  guess_rank: boolean | null;
  hangout: string | null;
  icon: Generated<string | null>;
  last_updated_at: Timestamp | null;
  name: Generated<string | null>;
  personality: number | null;
  platform: number[] | null;
  seasons: number[] | null;
  spirit: number | null;
  user_id: string;
  winged_light: number | null;
}

export interface Users {
  artist: boolean | null;
  crowdin_user_id: number | null;
  discord_user_id: string;
  supporter: boolean | null;
  translator: boolean | null;
}

export interface Welcome {
  accent_colour: number | null;
  asset: string | null;
  guild_id: string;
  hug: boolean | null;
  message: string | null;
  welcome_channel_id: string | null;
}

export interface DB {
  bluesky_webhooks: BlueskyWebhooks;
  catalogue: Catalogue;
  checklist: Checklist;
  daily_guides: DailyGuides;
  daily_guides_distribution: DailyGuidesDistribution;
  feedback: Feedback;
  feedback_upsell: FeedbackUpsell;
  friendship_actions: FriendshipActions;
  giveaway: Giveaway;
  giveaway_upsell: GiveawayUpsell;
  guess: Guess;
  hearts: Hearts;
  messages: Messages;
  notifications: Notifications;
  sky_profile_likes: SkyProfileLikes;
  sky_profiles: SkyProfiles;
  users: Users;
  welcome: Welcome;
}
