import { resolveOffer } from "../Utility/catalogue.js";
import { LARGE_PLACEABLE_PROPS_EMOJIS, SMALL_PLACEABLE_PROPS_EMOJIS } from "../Utility/emojis.js";

const items = resolveOffer([
	{
		name: "Stone single bench",
		bit: 1 << 0,
		cost: { candles: 32 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp43,
	},
	{
		name: "Stone wood-fired oven",
		bit: 1 << 1,
		cost: { ascendedCandles: 35 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp44,
	},
	{
		name: "Stone single bed",
		bit: 1 << 2,
		cost: { hearts: 24 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp45,
	},
	{
		name: "Stone tall cube",
		bit: 1 << 3,
		cost: { candles: 88 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp46,
	},
	{
		name: "Stone chair",
		bit: 1 << 4,
		cost: { candles: 64 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp47,
	},
	{
		name: "Stone small table",
		bit: 1 << 5,
		cost: { candles: 20 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp48,
	},
	{
		name: "Decor pillow one colour",
		bit: 1 << 6,
		cost: { candles: 32 },
		emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp43,
	},
	{
		name: "Stone tall shelf",
		bit: 1 << 7,
		cost: { ascendedCandles: 30 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp49,
	},
	{
		name: "Stone bench",
		bit: 1 << 8,
		cost: { candles: 60 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp51,
	},
	{
		name: "Stone desk",
		bit: 1 << 9,
		cost: { candles: 50 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp52,
	},
	{
		name: "Decor pillow two colour",
		bit: 1 << 10,
		cost: { hearts: 48 },
		emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp45,
	},
	{
		name: "Small solid rug",
		bit: 1 << 11,
		cost: { candles: 25 },
		emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp46,
	},
	{
		name: "Stone armchair",
		bit: 1 << 12,
		cost: { hearts: 20 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp53,
	},
	{
		name: "Stone console table",
		bit: 1 << 13,
		cost: { candles: 45 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp54,
	},
	{
		name: "Decor folded cloth",
		bit: 1 << 14,
		cost: { hearts: 40 },
		emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp47,
	},
	{
		name: "Small stripes rug",
		bit: 1 << 15,
		cost: { candles: 35 },
		emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp48,
	},
	{
		name: "Stone loveseat",
		bit: 1 << 16,
		cost: { hearts: 33 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp55,
	},
	{
		name: "Stone round dining table",
		bit: 1 << 17,
		cost: { hearts: 18 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp56,
	},
	{
		name: "Stone plant stand",
		bit: 1 << 18,
		cost: { hearts: 24 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp57,
	},
	{
		name: "Small classic rug",
		bit: 1 << 19,
		cost: { hearts: 15 },
		emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp49,
	},
	{
		name: "Stone sofa corner",
		bit: 1 << 20,
		cost: { candles: 25 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp58,
	},
	{
		name: "Stone square dining table",
		bit: 1 << 21,
		cost: { hearts: 23 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp59,
	},
	{
		name: "Stone wall sconce",
		bit: 1 << 22,
		cost: { ascendedCandles: 32 },
		emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp50,
	},
	{
		name: "Small half-circle rug",
		bit: 1 << 23,
		cost: { candles: 45 },
		emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp51,
	},
	{
		name: "Stone sofa side",
		bit: 1 << 24,
		cost: { candles: 80 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp60,
	},
	{
		name: "Stone long dining table",
		bit: 1 << 25,
		cost: { hearts: 33 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp61,
	},
	{
		name: "Stone small bathtub",
		bit: 1 << 26,
		cost: { hearts: 25 },
		emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp62,
	},
	{
		name: "Medium solid rug",
		bit: 1 << 27,
		cost: { candles: 40 },
		emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp52,
	},
	{
		name: "Stone figurine",
		bit: 1 << 28,
		cost: { ascendedCandles: 99 },
		emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp53,
	},
	// From this point onwards, there are too many bits.
	// {
	// 	name: "Stone kichen drawers",
	// 	bit: 1 << 29,
	// 	cost: { candles: 50 },
	// 	emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp63,
	// },
	// {
	// 	name: "Stone coffee table",
	// 	bit: 1 << 30,
	// 	cost: { ascendedCandles: 28 },
	// 	emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp64,
	// },
	// {
	// 	name: "Stone candle light",
	// 	bit: 1 << 31,
	// 	cost: { ascendedCandles: 32 },
	// 	emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp65,
	// },
	// {
	// 	name: "Medium stripes rug",
	// 	bit: 1 << 32,
	// 	cost: { candles: 50 },
	// 	emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp54,
	// },
	// {
	// 	name: "Instrument stand",
	// 	bit: 1 << 33,
	// 	cost: { ascendedCandles: 33 },
	// 	emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp55,
	// },
	// {
	// 	name: "Stone wall pot rack",
	// 	bit: 1 << 34,
	// 	cost: { candles: 50 },
	// 	emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp56,
	// },
	// {
	// 	name: "Stone closed box",
	// 	bit: 1 << 35,
	// 	cost: { candles: 30 },
	// 	emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp57,
	// },
	// {
	// 	name: "Stone washstand",
	// 	bit: 1 << 36,
	// 	cost: { candles: 40 },
	// 	emoji: LARGE_PLACEABLE_PROPS_EMOJIS.LargePlaceableProp66,
	// },
	// {
	// 	name: "Medium diamonds rug",
	// 	bit: 1 << 37,
	// 	cost: { hearts: 18 },
	// 	emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp58,
	// },
	// {
	// 	name: "Music player",
	// 	bit: 1 << 38,
	// 	cost: { ascendedCandles: 66 },
	// 	emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp59,
	// },
	// {
	// 	name: "Stone empty box",
	// 	bit: 1 << 39,
	// 	cost: { candles: 30 },
	// 	emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp60,
	// },
	// {
	// 	name: "Stone wall mirror",
	// 	bit: 1 << 40,
	// 	cost: { candles: 60 },
	// 	emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp61,
	// },
	// {
	// 	name: "Medium argyle rug",
	// 	bit: 1 << 41,
	// 	cost: { hearts: 20 },
	// 	emoji: SMALL_PLACEABLE_PROPS_EMOJIS.SmallPlaceableProp62,
	// },
]);

export const NESTING_WORKSHOP = {
	items,
	maximumItemsBit: items.reduce((bits, { bit }) => bit | bits, 0),
} as const;
