name: Deploy Servare
on:
  push:
    branches:
      - main
    paths:
      - apps/servare/**/*
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --config apps/servare/fly.toml --dockerfile apps/servare/Dockerfile --remote-only --access-token $FLY_DEPLOY_TOKEN
        env:
          FLY_DEPLOY_TOKEN: ${{ secrets.FLY_DEPLOY_SERVARE_TOKEN }}
