name: Deploy Notifications
on:
  push:
    branches:
      - main
    paths:
      - apps/reddit/**/*
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --config apps/reddit/fly.toml --dockerfile apps/reddit/Dockerfile --remote-only --access-token $FLY_DEPLOY_TOKEN
        env:
          FLY_DEPLOY_TOKEN: ${{ secrets.FLY_DEPLOY_THATSKYAPPLICATION_REDDIT_TOKEN }}
