name: Deploy commands
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  deploy:
    name: Deploy commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1.

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10.

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0.
        with:
          cache: pnpm
          node-version-file: package.json

      - name: Install dependencies
        run: pnpm --filter @thatskyapplication/caelus... install

      - name: Build dependencies
        run: pnpm --filter @thatskyapplication/caelus^... run build

      - name: Deploy commands
        run: pnpm --filter @thatskyapplication/caelus run deploy-commands
        env:
          GITHUB_ACTIONS: true
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          SUPPORT_SERVER_GUILD_ID: ${{ vars.SUPPORT_SERVER_GUILD_ID }}
          TOP_GG_TOKEN: ${{ secrets.TOP_GG_TOKEN }}
