name: Deploy Sky Elder
on:
  workflow_dispatch:
    inputs:
      semver:
        description: SemVer
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
permissions:
  contents: read
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1.

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10.

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0.
        with:
          cache: pnpm
          node-version-file: package.json

      - name: Install dependencies
        run: pnpm install

      - name: Build dependencies
        run: pnpm --filter @thatskyapplication/sky-elder... run build

      - name: Deploy Sky Elder
        working-directory: apps/sky-elder
        run: |
          if [ -z "$DEVVIT_AUTH_TOKEN" ]; then
            echo "::error::Missing DEVVIT_AUTH_TOKEN."
            exit 1
          fi

          pnpm exec devvit publish --bump "$SEMVER"
        env:
          SEMVER: ${{ inputs.semver }}
          DEVVIT_ALLOW_SOURCE_UPLOAD: "1"
          DEVVIT_AUTH_TOKEN: ${{ secrets.DEVVIT_AUTH_TOKEN }}
