name: Deploy Caelus codebase
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy Caelus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only --access-token $FLY_DEPLOY_TOKEN
        env:
          FLY_DEPLOY_TOKEN: ${{ secrets.FLY_DEPLOY_TOKEN }}
