name: Deploy commands
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  deploy:
    name: Deploy commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1.

      - name: Install pnpm and Node.js
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0.
        with:
          install: false

      - name: Install dependencies
        run: pnpm --filter @thatskyapplication/caelus... install

      - name: Build dependencies
        run: pnpm --filter @thatskyapplication/caelus^... run build

      - name: Deploy commands
        run: pnpm --filter @thatskyapplication/caelus run deploy-commands
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          SUPPORT_SERVER_GUILD_ID: ${{ vars.SUPPORT_SERVER_GUILD_ID }}
          TOP_GG_TOKEN: ${{ secrets.TOP_GG_TOKEN }}
